BEGIN;

INSERT INTO hierarchy_class (id, class) VALUES (1, 'Oligochaeta');
INSERT INTO hierarchy_class (id, class) VALUES (2, 'Polychaeta');
INSERT INTO hierarchy_class (id, class) VALUES (3, 'Arachnida');
INSERT INTO hierarchy_class (id, class) VALUES (4, 'Branchiopoda');
INSERT INTO hierarchy_class (id, class) VALUES (5, 'Chilopoda');
INSERT INTO hierarchy_class (id, class) VALUES (6, 'Diplopoda');
INSERT INTO hierarchy_class (id, class) VALUES (7, 'Entognatha');
INSERT INTO hierarchy_class (id, class) VALUES (8, 'Insecta');
INSERT INTO hierarchy_class (id, class) VALUES (9, 'Malacostraca');
INSERT INTO hierarchy_class (id, class) VALUES (10, 'Maxillopoda');
INSERT INTO hierarchy_class (id, class) VALUES (11, 'Rhynchonellata');
INSERT INTO hierarchy_class (id, class) VALUES (12, 'Actinopterygii');
INSERT INTO hierarchy_class (id, class) VALUES (13, 'Amphibia');
INSERT INTO hierarchy_class (id, class) VALUES (14, 'Aves');
INSERT INTO hierarchy_class (id, class) VALUES (15, 'Elasmobranchii');
INSERT INTO hierarchy_class (id, class) VALUES (16, 'Holocephali');
INSERT INTO hierarchy_class (id, class) VALUES (17, 'Mammalia');
INSERT INTO hierarchy_class (id, class) VALUES (18, 'Myxini');
INSERT INTO hierarchy_class (id, class) VALUES (19, 'Reptilia');
INSERT INTO hierarchy_class (id, class) VALUES (20, 'Sarcopterygii');
INSERT INTO hierarchy_class (id, class) VALUES (21, 'Anthozoa');
INSERT INTO hierarchy_class (id, class) VALUES (22, 'Hydrozoa');
INSERT INTO hierarchy_class (id, class) VALUES (23, 'Asteroidea');
INSERT INTO hierarchy_class (id, class) VALUES (24, 'Crinoidea');
INSERT INTO hierarchy_class (id, class) VALUES (25, 'Echinoidea');
INSERT INTO hierarchy_class (id, class) VALUES (26, 'Holothuroidea');
INSERT INTO hierarchy_class (id, class) VALUES (27, 'Enteropneusta');
INSERT INTO hierarchy_class (id, class) VALUES (28, 'Bivalvia');
INSERT INTO hierarchy_class (id, class) VALUES (29, 'Cephalopoda');
INSERT INTO hierarchy_class (id, class) VALUES (30, 'Gastropoda');
INSERT INTO hierarchy_class (id, class) VALUES (31, 'Onychophora');
INSERT INTO hierarchy_class (id, class) VALUES (32, 'Calcarea');
INSERT INTO hierarchy_class (id, class) VALUES (33, 'Demospongiae');
INSERT INTO hierarchy_class (id, class) VALUES (34, 'Hexactinellida');
INSERT INTO hierarchy_class (id, class) VALUES (35, 'Sipunculidea');

END;