BEGIN;

-- Specie data 
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (1, 'Abelha', 1, 'Apis mellifera scutellata', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (2, 'Ácaro da Sarna', 2, 'Sarcoptes scabei', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (3, 'Águia chilena', 3, 'Geranoaetus melanoleucus', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (4, 'Águia cinzenta', 4, 'Harpyhaliaetus coronatus', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (5, 'Águia dourada', 5, 'Aquila chrysaetus', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (6, 'Albatroz', 6, 'Thalassarche melanophris', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (7, 'Alce', 7, 'Alces alce', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (8, 'Anta', 8, 'Tapirus terrestris', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (9, 'Antrax (bacilo do)', 9, 'Bacillus anthracis', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (10, 'Aranha caranguejeira ', 1, 'Grammostola mollicoma', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (11, 'Aranha marrom', 2, 'Loxosceles spp', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (12, 'Araponga', 3, 'Procnias nudicollis', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (13, 'Arara vermelha', 4, 'Ara macao', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (14, 'Aratu', 5, 'Aratus pisoni', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (15, 'Asno', 6, 'Equus asinus', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (16, 'Avestruz', 7, 'Struthio camelus', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (17, 'Bacilo do tifo', 8, 'Salmonella tiphosa', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (18, 'Baleia azul', 9, 'Baleanoptera musculus', 3, 3, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (19, 'Barata', 1, 'Blatta orientalis', 1, 1, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (20, 'Beija-flor ', 2, 'Hylocartis cyanus', 2, 2, NULL, 1, 1, 1, 1);
INSERT INTO species(id, common_name, extinction_risk_category, scientific_name, conservation_id, cover_map_id, cover_photo_id, distribution_id, natural_history_id, taxonomy_id, threat_id) VALUES (21, 'Arara-azul-de-lear', 0, 'Anodorhynchus leari', NULL, NULL, NULL, NULL, NULL, 1, NULL);

END;
