package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.DensityData;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.ExtinctionRiskConfiguration;
import com.unep.wcmc.model.Habitat;
import com.unep.wcmc.model.NaturalHistory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.TrendOccurence;
import com.unep.wcmc.model.Threat;

global Species species;
global java.util.List configuration;

/**
 * Critically Endangered (CR) rules
 */
rule "Critically Endangered (CR) - A1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        PopulationTrend(percPopulationDecline >= $config.percPopulationDecline) // A1
        PopulationTrend(declineReversibleAndCeased == null)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end

rule "Critically Endangered (CR) - A2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        PopulationTrend(percPopulationDecline >= $config.percePopulationDecline2) // A2, A3, A4
        PopulationTrend(declineReversibleAndCeased == false)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end

rule "Critically Endangered (CR) - B"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= $config.occurrenceExtent) or
        DistributionArea(occupancyArea <= $config.occupancyArea)
        // others
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber == 1)
        )
    and
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber == 1)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end

rule "Critically Endangered (CR) - C"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber <=  $config.numberMatureIndividuals)
        (
            PopulationDynamics(declinePeriodPercent >= 25) or
            PopulationDynamics(matureIndividualsSubpopulationMaxNumber <= 50) or
            PopulationDynamics(imatureIndividualsSubpopulationPercent >= 90) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end

rule "Critically Endangered (CR) - D"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber <=  $config.numberMatureIndividuals2)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end


rule "Critically Endangered (CR) - E"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.CRITICALLY_ENDANGERED) from configuration
        // criteria
        PopulationTrend(brazilExtinctionProbability >= $config.probExtinctionInWild)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.CRITICALLY_ENDANGERED);
end