package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Conservation;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Specie
import com.unep.wcmc.model.Taxonomy;

global Specie specie;

rule "Data Deficient (DD)"
    activation-group "ExtinctionRisk"
    salience 10
    when
        Taxonomy(limitationsForAssessment == true)
    or
        Taxonomy(limitationsForAssessment == false)
        Conservation(extinctionRisk.inNationalEndangeredFauna == null || extinctionRisk.inNationalEndangeredFauna == true)
        DistributionArea(onlyFromFewLocalities == true, (regionIsWellSampled == false || regionIsWellSampled == null))
    then
        specie.setExtinctionRiskCategory(ExtinctionRiskCategory.DATA_DEFICIENT);
end