package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.DensityData;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.ExtinctionRiskConfiguration;
import com.unep.wcmc.model.Habitat;
import com.unep.wcmc.model.NaturalHistory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.TrendOccurence;
import com.unep.wcmc.model.Threat;

global Species species;
global java.util.List configuration;

/**
 * Endangered (EN) rules
 */
rule "Endangered (EN) - A1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        PopulationTrend(declineReversibleAndCeased == null)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - A2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        PopulationTrend(declineReversibleAndCeased == false)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING)
        (
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B3"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        Habitat(continuingDeclineInHabitatQuality == true)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B4"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B5"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B6"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B7"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        PopulationDynamics(populationSeverelyFragmented == true)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            Threat(geographicallyDistinctAreasNumber <= 5)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - B8"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 5000, extendOccurrence > 100) or
        DistributionArea(occupancyArea <= 500, occupancyArea > 10)
        // others
        Threat(geographicallyDistinctAreasNumber <= 5)
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - C"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber <=  $config.numberMatureIndividuals)
        (
            PopulationDynamics(declinePeriodPercent >= 20) or
            PopulationDynamics(matureIndividualsSubpopulationMaxNumber <= 250) or
            PopulationDynamics(imatureIndividualsSubpopulationPercent >= 95) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end

rule "Endangered (EN) - D"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber <=  $config.numberMatureIndividuals2)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end


rule "Endangered (EN) - E"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.ENDANGERED) from configuration
        // criteria
        PopulationTrend(brazilExtinctionProbability >= $config.probExtinctionInWild)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.ENDANGERED);
end
