package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Specie;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.ExtinctionRisk
import com.unep.wcmc.model.ExtinctionRiskCategory;

global Specie specie;

rule "Extinct (EX)"
    when
        PopulationDynamics(captiveBreedingProgram == false)
        ExtinctionRisk(nationalEvaluationElegible == true)
    then
        specie.setExtinctionRiskCategory(ExtinctionRiskCategory.EXTINCT);
        System.out.println("Extinct (EX)");
end

rule "Extinct in the Wild (EW)"
    when
        PopulationDynamics(captiveBreedingProgram == true)
        ExtinctionRisk(nationalEvaluationElegible == true)
    then
        specie.setExtinctionRiskCategory(ExtinctionRiskCategory.EXTINCT_IN_THE_WILD);
        System.out.println("Extinct in the Wild (EW)");
end

rule "Regionally Extinct (RE)"
    when
        PopulationDynamics(captiveBreedingProgram == false)
        ExtinctionRisk(nationalEvaluationElegible == false)
    then
        specie.setExtinctionRiskCategory(ExtinctionRiskCategory.REGIONALLY_EXTINCT);
        System.out.println("Regionally Extinct (RE)");
end
