package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.ExtinctionRisk
import com.unep.wcmc.model.ExtinctionRiskCategory;

global Species species;

rule "Extinct in the Wild (EW)"
    activation-group "ExtinctionRisk"
    salience 10
    when
        PopulationDynamics(matureIndividualsNumber == 0)
        // Captive breeding program for the species = YES  Endemic from Brazil = YES
        PopulationDynamics(captiveBreedingProgram == true)
        ExtinctionRisk(nationalEvaluationElegible == true)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.EXTINCT_IN_THE_WILD);
end