package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Conservation;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.Taxonomy;

global Species species;

/*
 * Non-threatened species, which do not fit into other categories.
 */
rule "Least Concern (LC)"
    activation-group "ExtinctionRisk"
    salience 10
    when
        Taxonomy(limitationsForAssessment == false)
        DistributionArea(onlyFromFewLocalities == true)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.LEAST_CONCERN);
end




