package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Conservation;
import com.unep.wcmc.model.DensityData;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.ExtinctionRiskConfiguration;
import com.unep.wcmc.model.Habitat;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.Taxonomy;
import com.unep.wcmc.model.Threat;
import com.unep.wcmc.model.TrendOccurence;

global Species species;
global java.util.List configuration;

/**
 * Near Threatened (NT) rules
 */
rule "Near Threatened (NT) - A1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        PopulationTrend(percPopulationDecline >= $config.percPopulationDecline, percPopulationDecline < 50) // A1
        PopulationTrend(declineReversibleAndCeased == null)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end

rule "Near Threatened (NT) - A2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        PopulationTrend(percPopulationDecline >= $config.percePopulationDecline2, percPopulationDecline < 40) // A2, A3, A4
        PopulationTrend(declineReversibleAndCeased == false)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end

rule "Near Threatened (NT) - B1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 30000, extendOccurrence > 2000) or
        DistributionArea(occupancyArea <= 3000, occupancyArea > 2000)
        // others
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 10)
        )
    and
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 10)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end


rule "Near Threatened (NT) - B2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        // B1,B2 (EOD or AOD)
        DistributionArea(extendOccurrence <= 20000, extendOccurrence > 5000) or
        DistributionArea(occupancyArea <= 2000, occupancyArea > 500)
        // others
        (
            DistributionArea(trendExtendOccurence == TrendOccurence.DECLINING) or
            DistributionArea(trendOccupancyArea == TrendOccurence.DECLINING) or
            Habitat(continuingDeclineInHabitatQuality == true) or
            PopulationDynamics(matureIndividualsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(extremeFlutuationInMatureIndividualsNumber == true) or
            DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING) or
            PopulationDynamics(populationSeverelyFragmented == true) or
            Threat(geographicallyDistinctAreasNumber <= 10)
        )
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end

rule "Near Threatened (NT) - C1"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber >  10000, matureIndividualsNumber < 15000)
        PopulationDynamics(declinePeriodPercent <= 10)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end

rule "Near Threatened (NT) - C2"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsSubpopulationMaxNumber > 1000, matureIndividualsNumber <= 1500)
        DensityData(subPopulationsNumberTrend == TrendOccurence.DECLINING)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end

rule "Near Threatened (NT) - C3"
    activation-group "ExtinctionRisk"
    salience 0
    when
        $config : ExtinctionRiskConfiguration(category == ExtinctionRiskCategory.NEAR_THREATENED) from configuration
        // criteria
        PopulationDynamics(matureIndividualsNumber >  1000, matureIndividualsNumber <= 1500)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NEAR_THREATENED);
end