package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.Conservation;
import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.PopulationTrend;
import com.unep.wcmc.model.Species;
import com.unep.wcmc.model.Taxonomy;

global Species species;

/*
 * Not Applicable (NA) rules
 */
rule "Not Applicable (NA)"
    activation-group "ExtinctionRisk"
    salience 10
    when
        Conservation(extinctionRisk.inNationalEndangeredFauna == false)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.NOT_APPLICABLE);
end