package rules.extinction.risk;
dialect  "mvel"

import com.unep.wcmc.model.DistributionArea;
import com.unep.wcmc.model.ExtinctionRisk
import com.unep.wcmc.model.ExtinctionRiskCategory;
import com.unep.wcmc.model.PopulationDynamics;
import com.unep.wcmc.model.Species;

global Species species;

rule "Regionally Extinct (RE)"
    activation-group "ExtinctionRisk"
    salience 10
    when
        PopulationDynamics(matureIndividualsNumber == 0)
        // Captive breeding program for the species = NO  Endemic from Brazil = NO
        PopulationDynamics(captiveBreedingProgram == false)
        DistributionArea(endemicFromBrazil == false)
    then
        species.setExtinctionRiskCategory(ExtinctionRiskCategory.REGIONALLY_EXTINCT);
end
