
-- Kingdom data
INSERT INTO kingdom (id, name) VALUES (1, 'Animalia');

-- Phylum data
INSERT INTO phylum (id, phylum) VALUES (1, 'Annelida');
INSERT INTO phylum (id, phylum) VALUES (2, 'Arthropoda');
INSERT INTO phylum (id, phylum) VALUES (3, 'Brachiopoda');
INSERT INTO phylum (id, phylum) VALUES (4, 'Chordata');
INSERT INTO phylum (id, phylum) VALUES (6, 'Cnidaria');
INSERT INTO phylum (id, phylum) VALUES (7, 'Echinodermata');
INSERT INTO phylum (id, phylum) VALUES (8, 'Hemichordata');
INSERT INTO phylum (id, phylum) VALUES (9, 'Mollusca');
INSERT INTO phylum (id, phylum) VALUES (10, 'Onychophora');
INSERT INTO phylum (id, phylum) VALUES (11, 'Porifera');
INSERT INTO phylum (id, phylum) VALUES (12, 'Sipuncula');


-- HierarchyClass data
INSERT INTO hierarchy_class (id, class) VALUES (1, 'Actinopterygii');
INSERT INTO hierarchy_class (id, class) VALUES (2, 'Amphibia');
INSERT INTO hierarchy_class (id, class) VALUES (3, 'Anthozoa');
INSERT INTO hierarchy_class (id, class) VALUES (4, 'Arachnida');
INSERT INTO hierarchy_class (id, class) VALUES (5, 'Asteroidea');
INSERT INTO hierarchy_class (id, class) VALUES (6, 'Aves');
INSERT INTO hierarchy_class (id, class) VALUES (7, 'Bivalvia');
INSERT INTO hierarchy_class (id, class) VALUES (8, 'Branchiopoda');
INSERT INTO hierarchy_class (id, class) VALUES (9, 'Calcarea');
INSERT INTO hierarchy_class (id, class) VALUES (10, 'Cephalopoda');
INSERT INTO hierarchy_class (id, class) VALUES (11, 'Chilopoda');
INSERT INTO hierarchy_class (id, class) VALUES (12, 'Crinoidea');
INSERT INTO hierarchy_class (id, class) VALUES (13, 'Demospongiae');
INSERT INTO hierarchy_class (id, class) VALUES (14, 'Diplopoda');
INSERT INTO hierarchy_class (id, class) VALUES (15, 'Echinoidea');
INSERT INTO hierarchy_class (id, class) VALUES (16, 'Elasmobranchii');
INSERT INTO hierarchy_class (id, class) VALUES (17, 'Enteropneusta');
INSERT INTO hierarchy_class (id, class) VALUES (18, 'Entognatha');
INSERT INTO hierarchy_class (id, class) VALUES (19, 'Gastropoda');
INSERT INTO hierarchy_class (id, class) VALUES (20, 'Hexactinellida');
INSERT INTO hierarchy_class (id, class) VALUES (21, 'Holocephali');
INSERT INTO hierarchy_class (id, class) VALUES (22, 'Holothuroidea');
INSERT INTO hierarchy_class (id, class) VALUES (23, 'Hydrozoa');
INSERT INTO hierarchy_class (id, class) VALUES (24, 'Insecta');
INSERT INTO hierarchy_class (id, class) VALUES (25, 'Malacostraca');
INSERT INTO hierarchy_class (id, class) VALUES (26, 'Mammalia');
INSERT INTO hierarchy_class (id, class) VALUES (27, 'Maxillopoda');
INSERT INTO hierarchy_class (id, class) VALUES (28, 'Myxini');
INSERT INTO hierarchy_class (id, class) VALUES (29, 'Oligochaeta');
INSERT INTO hierarchy_class (id, class) VALUES (30, 'Onychophora');
INSERT INTO hierarchy_class (id, class) VALUES (31, 'Polychaeta');
INSERT INTO hierarchy_class (id, class) VALUES (32, 'Reptilia');
INSERT INTO hierarchy_class (id, class) VALUES (33, 'Rhynchonellata');
INSERT INTO hierarchy_class (id, class) VALUES (34, 'Sarcopterygii');
INSERT INTO hierarchy_class (id, class) VALUES (35, 'Sipunculidea');

-- HierarchyOrder data
INSERT INTO hierarchy_order (id, name) VALUES (1, 'Anura');
INSERT INTO hierarchy_order (id, name) VALUES (2, 'Caudata');
INSERT INTO hierarchy_order (id, name) VALUES (3, 'Gymnophiona');

-- Family data
INSERT INTO family (id, family) VALUES (1, 'Allophrynidae');
INSERT INTO family (id, family) VALUES (2, 'Aromobatidae');
INSERT INTO family (id, family) VALUES (3, 'Brachycephalidae');
INSERT INTO family (id, family) VALUES (4, 'Bufonidae');
INSERT INTO family (id, family) VALUES (5, 'Caeciliidae');
INSERT INTO family (id, family) VALUES (6, 'Centrolenidae');
INSERT INTO family (id, family) VALUES (7, 'Ceratophryidae');
INSERT INTO family (id, family) VALUES (8, 'Craugastoridae');
INSERT INTO family (id, family) VALUES (9, 'Cycloramphidae');
INSERT INTO family (id, family) VALUES (10, 'Dendrobatidae');
INSERT INTO family (id, family) VALUES (11, 'Eleutherodactylidae');
INSERT INTO family (id, family) VALUES (12, 'Hemiphractidae');
INSERT INTO family (id, family) VALUES (13, 'Hylidae');
INSERT INTO family (id, family) VALUES (14, 'Hylodidae');
INSERT INTO family (id, family) VALUES (15, 'Leiuperidae');
INSERT INTO family (id, family) VALUES (16, 'Leptodactylidae');
INSERT INTO family (id, family) VALUES (17, 'Microhylidae');
INSERT INTO family (id, family) VALUES (18, 'Odontophrynidae');
INSERT INTO family (id, family) VALUES (19, 'Pipidae');
INSERT INTO family (id, family) VALUES (20, 'Plethodontidae');
INSERT INTO family (id, family) VALUES (21, 'Ranidae');
INSERT INTO family (id, family) VALUES (22, 'Rhinatrematidae');
INSERT INTO family (id, family) VALUES (23, 'Siphonopidae');
INSERT INTO family (id, family) VALUES (24, 'Strabomantidae');
INSERT INTO family (id, family) VALUES (25, 'Typhlonectidae');

-- Genre data
INSERT INTO gender (id, gender) VALUES (1, 'Adelophryne');
INSERT INTO gender (id, gender) VALUES (2, 'Adelphobates');
INSERT INTO gender (id, gender) VALUES (3, 'Adenomera');
INSERT INTO gender (id, gender) VALUES (4, 'Agalychnis');
INSERT INTO gender (id, gender) VALUES (5, 'Allobates');
INSERT INTO gender (id, gender) VALUES (6, 'Allophryne');
INSERT INTO gender (id, gender) VALUES (7, 'Amazophrynella');
INSERT INTO gender (id, gender) VALUES (8, 'Ameerega');
INSERT INTO gender (id, gender) VALUES (9, 'Anomaloglossus');
INSERT INTO gender (id, gender) VALUES (10, 'Aparasphenodon');
INSERT INTO gender (id, gender) VALUES (11, 'Aplastodiscus');
INSERT INTO gender (id, gender) VALUES (12, 'Arcovomer');
INSERT INTO gender (id, gender) VALUES (13, 'Atelopus');
INSERT INTO gender (id, gender) VALUES (14, 'Atretochoana');
INSERT INTO gender (id, gender) VALUES (15, 'Barycholos');
INSERT INTO gender (id, gender) VALUES (16, 'Bokermannohyla');
INSERT INTO gender (id, gender) VALUES (17, 'Bolitoglossa');
INSERT INTO gender (id, gender) VALUES (18, 'Brachycephalus');
INSERT INTO gender (id, gender) VALUES (19, 'Brasilotyphlus');
INSERT INTO gender (id, gender) VALUES (20, 'Caecilia');
INSERT INTO gender (id, gender) VALUES (21, 'Calamita');
INSERT INTO gender (id, gender) VALUES (22, 'Ceratophrys');
INSERT INTO gender (id, gender) VALUES (23, 'Chiasmocleis');
INSERT INTO gender (id, gender) VALUES (24, 'Chthonerpeton');
INSERT INTO gender (id, gender) VALUES (25, 'Cochranella');
INSERT INTO gender (id, gender) VALUES (26, 'Corythomantis');
INSERT INTO gender (id, gender) VALUES (27, 'Crossodactylodes');
INSERT INTO gender (id, gender) VALUES (28, 'Crossodactylus');
INSERT INTO gender (id, gender) VALUES (29, 'Cruziohyla');
INSERT INTO gender (id, gender) VALUES (30, 'Ctenophryne');
INSERT INTO gender (id, gender) VALUES (31, 'Cycloramphus');
INSERT INTO gender (id, gender) VALUES (32, 'Dasypops');
INSERT INTO gender (id, gender) VALUES (33, 'Dendrobates');
INSERT INTO gender (id, gender) VALUES (34, 'Dendrophryniscus');
INSERT INTO gender (id, gender) VALUES (35, 'Dendropsophus');
INSERT INTO gender (id, gender) VALUES (36, 'Dermatonotus');
INSERT INTO gender (id, gender) VALUES (37, 'Ecnomiohyla');
INSERT INTO gender (id, gender) VALUES (38, 'Edalorhina');
INSERT INTO gender (id, gender) VALUES (39, 'Elachistocleis');
INSERT INTO gender (id, gender) VALUES (40, 'Engystomops');
INSERT INTO gender (id, gender) VALUES (41, 'Euparkerella');
INSERT INTO gender (id, gender) VALUES (42, 'Eupemphix');
INSERT INTO gender (id, gender) VALUES (43, 'Flectonotus');
INSERT INTO gender (id, gender) VALUES (44, 'Flectonotus');
INSERT INTO gender (id, gender) VALUES (45, 'Frostius');
INSERT INTO gender (id, gender) VALUES (46, 'Gastrotheca');
INSERT INTO gender (id, gender) VALUES (47, 'Haddadus');
INSERT INTO gender (id, gender) VALUES (48, 'Hamptophryne');
INSERT INTO gender (id, gender) VALUES (49, 'Hemiphractus');
INSERT INTO gender (id, gender) VALUES (50, 'Holoaden');
INSERT INTO gender (id, gender) VALUES (51, 'Hyalinobatrachium');
INSERT INTO gender (id, gender) VALUES (52, 'Hydrolaetare');
INSERT INTO gender (id, gender) VALUES (53, 'Hyla');
INSERT INTO gender (id, gender) VALUES (54, 'Hylodes');
INSERT INTO gender (id, gender) VALUES (55, 'Hyophryne');
INSERT INTO gender (id, gender) VALUES (56, 'Hypsiboas');
INSERT INTO gender (id, gender) VALUES (57, 'Ischnocnema');
INSERT INTO gender (id, gender) VALUES (58, 'Itapotihyla');
INSERT INTO gender (id, gender) VALUES (59, 'Leptodactylus');
INSERT INTO gender (id, gender) VALUES (60, 'Limnomedusa');
INSERT INTO gender (id, gender) VALUES (61, 'Lithobates');
INSERT INTO gender (id, gender) VALUES (62, 'Luetkenotyphlus');
INSERT INTO gender (id, gender) VALUES (63, 'Lysapsus');
INSERT INTO gender (id, gender) VALUES (64, 'Macrogenioglottus');
INSERT INTO gender (id, gender) VALUES (65, 'Megaelosia');
INSERT INTO gender (id, gender) VALUES (66, 'Melanophryniscus');
INSERT INTO gender (id, gender) VALUES (67, 'Microcaecilia');
INSERT INTO gender (id, gender) VALUES (68, 'Mimosiphonops');
INSERT INTO gender (id, gender) VALUES (69, 'Myersiella');
INSERT INTO gender (id, gender) VALUES (70, 'Nectocaecilia');
INSERT INTO gender (id, gender) VALUES (71, 'Noblella');
INSERT INTO gender (id, gender) VALUES (72, 'Odontophrynus');
INSERT INTO gender (id, gender) VALUES (73, 'Oerobates');
INSERT INTO gender (id, gender) VALUES (74, 'Oreophrynella');
INSERT INTO gender (id, gender) VALUES (75, 'Oscaecilia');
INSERT INTO gender (id, gender) VALUES (76, 'Osteocephalus');
INSERT INTO gender (id, gender) VALUES (77, 'Otophryne');
INSERT INTO gender (id, gender) VALUES (78, 'Paratelmatobius');
INSERT INTO gender (id, gender) VALUES (79, 'Phasmahyla');
INSERT INTO gender (id, gender) VALUES (80, 'Phrynomedusa');
INSERT INTO gender (id, gender) VALUES (81, 'Phyllodytes');
INSERT INTO gender (id, gender) VALUES (82, 'Phyllomedusa');
INSERT INTO gender (id, gender) VALUES (83, 'Physalaemus');
INSERT INTO gender (id, gender) VALUES (84, 'Phyzelaphryne');
INSERT INTO gender (id, gender) VALUES (85, 'Pipa');
INSERT INTO gender (id, gender) VALUES (86, 'Pleurodema');
INSERT INTO gender (id, gender) VALUES (87, 'Potomotyphlus');
INSERT INTO gender (id, gender) VALUES (88, 'Pristimantis');
INSERT INTO gender (id, gender) VALUES (89, 'Proceratophrys');
INSERT INTO gender (id, gender) VALUES (90, 'Pseudis');
INSERT INTO gender (id, gender) VALUES (91, 'Pseudopaludicola');
INSERT INTO gender (id, gender) VALUES (92, 'Ranitomeya');
INSERT INTO gender (id, gender) VALUES (93, 'Rhaebo');
INSERT INTO gender (id, gender) VALUES (94, 'Rhinatrema');
INSERT INTO gender (id, gender) VALUES (95, 'Rhinella');
INSERT INTO gender (id, gender) VALUES (96, 'Rupirana');
INSERT INTO gender (id, gender) VALUES (97, 'Scarthyla');
INSERT INTO gender (id, gender) VALUES (98, 'Scinax');
INSERT INTO gender (id, gender) VALUES (99, 'Scythrophrys');
INSERT INTO gender (id, gender) VALUES (100, 'Siphonops');
INSERT INTO gender (id, gender) VALUES (101, 'Sphaenorhynchus');
INSERT INTO gender (id, gender) VALUES (102, 'Stefania');
INSERT INTO gender (id, gender) VALUES (103, 'Stereocyclops');
INSERT INTO gender (id, gender) VALUES (104, 'Strabomantis');
INSERT INTO gender (id, gender) VALUES (105, 'Synapturanus');
INSERT INTO gender (id, gender) VALUES (106, 'Syncope');
INSERT INTO gender (id, gender) VALUES (107, 'Teratohyla');
INSERT INTO gender (id, gender) VALUES (108, 'Thoropa');
INSERT INTO gender (id, gender) VALUES (109, 'Trachycephalus');
INSERT INTO gender (id, gender) VALUES (110, 'Typhlonectes');
INSERT INTO gender (id, gender) VALUES (111, 'Vitreorana');
INSERT INTO gender (id, gender) VALUES (112, 'Xenohyla');
INSERT INTO gender (id, gender) VALUES (113, 'Zachaenus');


-- Threats data
INSERT INTO threat_category (id, description) VALUES (1, '0. No threat');
INSERT INTO threat_category (id, description) VALUES (2, '1.1. Agriculture rotation');
INSERT INTO threat_category (id, description) VALUES (3, '1.2. Small farms');
INSERT INTO threat_category (id, description) VALUES (4, '1.3. Agro-industrial agriculture');
INSERT INTO threat_category (id, description) VALUES (5, '1.4. Planting for logging on a small scale');
INSERT INTO threat_category (id, description) VALUES (6, '1.5. Planting for logging on a large scale');
INSERT INTO threat_category (id, description) VALUES (7, '1.6. Nomadic livestock');
INSERT INTO threat_category (id, description) VALUES (8, '1.7. Farming Small Properties');
INSERT INTO threat_category (id, description) VALUES (9, '1.8. Agro-industry Livestock');
INSERT INTO threat_category (id, description) VALUES (10, '1.9. marine aquaculture');
INSERT INTO threat_category (id, description) VALUES (11, '1.10. Freshwater Aquaculture');
INSERT INTO threat_category (id, description) VALUES (12, '2.1. Sand extraction');
INSERT INTO threat_category (id, description) VALUES (13, '2.2. Pebble extraction / stone');
INSERT INTO threat_category (id, description) VALUES (14, '2.3. Mineral extraction - underground');
INSERT INTO threat_category (id, description) VALUES (15, '2.4. Mineral extraction - mining');
INSERT INTO threat_category (id, description) VALUES (16, '2.5. Extraction of oil / oil');
INSERT INTO threat_category (id, description) VALUES (17, '2.6. Natural gas extraction');
INSERT INTO threat_category (id, description) VALUES (18, '2.7. Groundwater extraction');
INSERT INTO threat_category (id, description) VALUES (19, '3.1. Logging Subsistence / small scale');
INSERT INTO threat_category (id, description) VALUES (20, '3.2. Wood selective logging extraction');
INSERT INTO threat_category (id, description) VALUES (21, '3.3. Logging / deforestation');
INSERT INTO threat_category (id, description) VALUES (22, '3.4. Extraction of timber / wood for charcoal');
INSERT INTO threat_category (id, description) VALUES (23, '3.5. Not woody vegetation collection');
INSERT INTO threat_category (id, description) VALUES (24, '4.1.1. Industry Installation');
INSERT INTO threat_category (id, description) VALUES (25, '4.1.2. Working Industry');
INSERT INTO threat_category (id, description) VALUES (26, '4.2.1. Installation and operation of roads');
INSERT INTO threat_category (id, description) VALUES (27, '4.2.2. Installation and operation of railways');
INSERT INTO threat_category (id, description) VALUES (28, '4.2.3. Installation and operation of airports');
INSERT INTO threat_category (id, description) VALUES (29, '4.2.4. Installation and operation of ports and waterways');
INSERT INTO threat_category (id, description) VALUES (30, '4.3.1. Hydroelectric Power Plant (HPP)');
INSERT INTO threat_category (id, description) VALUES (31, '4.3.2. Small Hydroelectric Plant (SHP)');
INSERT INTO threat_category (id, description) VALUES (32, '4.3.3. Central Hydroelectric Generation (CGH)');
INSERT INTO threat_category (id, description) VALUES (33, '4.3.4. wind farm');
INSERT INTO threat_category (id, description) VALUES (34, '4.3.5. nuclear plant');
INSERT INTO threat_category (id, description) VALUES (35, '4.3.6. Power lines installation');
INSERT INTO threat_category (id, description) VALUES (36, '4.4. Infrastructure installation Tourism / recreation');
INSERT INTO threat_category (id, description) VALUES (37, '4.5. Telecommunications infrastructure installation');
INSERT INTO threat_category (id, description) VALUES (38, '4.6. Construction of dams / reservoirs to supply');
INSERT INTO threat_category (id, description) VALUES (39, '5.1. Rural settlements');
INSERT INTO threat_category (id, description) VALUES (40, '5.2. Boom towns');
INSERT INTO threat_category (id, description) VALUES (41, '6.1. Burned');
INSERT INTO threat_category (id, description) VALUES (42, '6.2. Natural origin of fire');
INSERT INTO threat_category (id, description) VALUES (43, '7.1. Introduction of exotic species (direct impact on the habitat)');
INSERT INTO threat_category (id, description) VALUES (44, '7.2. Competitors');
INSERT INTO threat_category (id, description) VALUES (45, '7.3. Predators');
INSERT INTO threat_category (id, description) VALUES (46, '7.4. Hybridization');
INSERT INTO threat_category (id, description) VALUES (47, '7.5. Pathogens / parasites');
INSERT INTO threat_category (id, description) VALUES (48, '7.6. Contact domestic species');
INSERT INTO threat_category (id, description) VALUES (49, '7.7. Other');
INSERT INTO threat_category (id, description) VALUES (50, '8.1. Use subsistence / local barter');
INSERT INTO threat_category (id, description) VALUES (51, '8.2. Sports');
INSERT INTO threat_category (id, description) VALUES (52, '8.3. Commercial');
INSERT INTO threat_category (id, description) VALUES (53, '8.4. Scientific collection');
INSERT INTO threat_category (id, description) VALUES (54, '8.5. Pest control');
INSERT INTO threat_category (id, description) VALUES (55, '8.6. Coral removal');
INSERT INTO threat_category (id, description) VALUES (56, '8.7. Other');
INSERT INTO threat_category (id, description) VALUES (57, '9.1. Running over');
INSERT INTO threat_category (id, description) VALUES (58, '9.2. Collisions Torres and Buildings');
INSERT INTO threat_category (id, description) VALUES (59, '9.3. Poisoning');
INSERT INTO threat_category (id, description) VALUES (60, '9.4. Other');
INSERT INTO threat_category (id, description) VALUES (61, '10.1. Global / ocean warming');
INSERT INTO threat_category (id, description) VALUES (62, '10.2. Acid rain');
INSERT INTO threat_category (id, description) VALUES (63, '10.3. Effects of the holes in the ozone layer');
INSERT INTO threat_category (id, description) VALUES (64, '10.4. Smoke');
INSERT INTO threat_category (id, description) VALUES (65, '10.5. Soil pollution - origin in agriculture');
INSERT INTO threat_category (id, description) VALUES (66, '10.6. Soil pollution - domestic origin');
INSERT INTO threat_category (id, description) VALUES (67, '10.7. Soil pollution - Source Commercial / Industrial');
INSERT INTO threat_category (id, description) VALUES (68, '10.8. Light pollution');
INSERT INTO threat_category (id, description) VALUES (69, '10.9. Noise pollution');
INSERT INTO threat_category (id, description) VALUES (70, '10.10. Water pollution - agricultural sources');
INSERT INTO threat_category (id, description) VALUES (71, '10:11. Water pollution - domestic origin');
INSERT INTO threat_category (id, description) VALUES (72, '10:12. Water pollution - commercial origin / Industrial');
INSERT INTO threat_category (id, description) VALUES (73, '10:13. Thermal pollution');
INSERT INTO threat_category (id, description) VALUES (74, '10:14. Oil spill');
INSERT INTO threat_category (id, description) VALUES (75, '10:15. Siltation');
INSERT INTO threat_category (id, description) VALUES (76, '10:16. Dump waste / sewage - source in the city');
INSERT INTO threat_category (id, description) VALUES (77, '10:16. Dump waste / sewage - source in the industry');
INSERT INTO threat_category (id, description) VALUES (78, '10:17. Disposal of solid waste - originated in the city');
INSERT INTO threat_category (id, description) VALUES (79, '10:17. Disposal of solid waste - source in the industry');
INSERT INTO threat_category (id, description) VALUES (80, '10:18. Noise pollution of waters');
INSERT INTO threat_category (id, description) VALUES (81, '10:19. Other');
INSERT INTO threat_category (id, description) VALUES (82, '11.1. Drought');
INSERT INTO threat_category (id, description) VALUES (83, '11.2. Storms / floods');
INSERT INTO threat_category (id, description) VALUES (84, '11.3. Thermal extremes');
INSERT INTO threat_category (id, description) VALUES (85, '11.4. Landslides');
INSERT INTO threat_category (id, description) VALUES (86, '11.5. Other');
INSERT INTO threat_category (id, description) VALUES (87, '12.1. Competitors');
INSERT INTO threat_category (id, description) VALUES (88, '12.2. Predators');
INSERT INTO threat_category (id, description) VALUES (89, '12.3. Prey / food base');
INSERT INTO threat_category (id, description) VALUES (90, '12.4. Hybridization');
INSERT INTO threat_category (id, description) VALUES (91, '12.5. Pathogens / parasites');
INSERT INTO threat_category (id, description) VALUES (92, '12.6. Other');
INSERT INTO threat_category (id, description) VALUES (93, '13.1.1. Surface longline');
INSERT INTO threat_category (id, description) VALUES (94, '13.1.2. Bottom longline');
INSERT INTO threat_category (id, description) VALUES (95, '13.1.3. Hand line');
INSERT INTO threat_category (id, description) VALUES (96, '13.1.4. Coastal gill surface');
INSERT INTO threat_category (id, description) VALUES (97, '13.1.5. Coastal gill background');
INSERT INTO threat_category (id, description) VALUES (98, '13.1.6. Oceanic gill surface');
INSERT INTO threat_category (id, description) VALUES (99, '13.1.7. Oceanic driftnet background');
INSERT INTO threat_category (id, description) VALUES (100, '13.1.8. Bottom trawling');
INSERT INTO threat_category (id, description) VALUES (101, '13.1.9. Coastal trawl double bottom');
INSERT INTO threat_category (id, description) VALUES (102, '13.1.10. Ocean trawl background (single and double)');
INSERT INTO threat_category (id, description) VALUES (103, '01.13.11. Drag (half water)');
INSERT INTO threat_category (id, description) VALUES (104, '01.13.12. siege');
INSERT INTO threat_category (id, description) VALUES (105, '13.1.13. creels');
INSERT INTO threat_category (id, description) VALUES (106, '13.01.14. puçá');
INSERT INTO threat_category (id, description) VALUES (107, '13.1.15. Underwater manual collection');
INSERT INTO threat_category (id, description) VALUES (108, '13.01.16. other');
INSERT INTO threat_category (id, description) VALUES (109, '13.2.1. single line');
INSERT INTO threat_category (id, description) VALUES (110, '13.2.2. paternoster');
INSERT INTO threat_category (id, description) VALUES (111, '13.2.3. Seine');
INSERT INTO threat_category (id, description) VALUES (112, '13.2.4. Drift Network');
INSERT INTO threat_category (id, description) VALUES (113, '13.2.5. Gill net (gillnets)');
INSERT INTO threat_category (id, description) VALUES (114, '13.2.6. drag');
INSERT INTO threat_category (id, description) VALUES (115, '13.2.7. flue');
INSERT INTO threat_category (id, description) VALUES (116, '13.2.8. hook');
INSERT INTO threat_category (id, description) VALUES (117, '13.2.9. harpoon');
INSERT INTO threat_category (id, description) VALUES (118, '13.2.10. corral');
INSERT INTO threat_category (id, description) VALUES (119, '13.2.11. Archery');
INSERT INTO threat_category (id, description) VALUES (120, '13.2.12. Puça');
INSERT INTO threat_category (id, description) VALUES (121, '13.2.13. underwater');
INSERT INTO threat_category (id, description) VALUES (122, '13.02.14. of Trolling');
INSERT INTO threat_category (id, description) VALUES (123, '13.02.15. Barranco');
INSERT INTO threat_category (id, description) VALUES (124, '13.2.16. with Fly');
INSERT INTO threat_category (id, description) VALUES (125, '13.2.17. Beach');
INSERT INTO threat_category (id, description) VALUES (126, '13.2.18. Round');
INSERT INTO threat_category (id, description) VALUES (127, '13.2.19. other');
INSERT INTO threat_category (id, description) VALUES (128, '13.3. Industrial fishing');
INSERT INTO threat_category (id, description) VALUES (129, '13.4. Small-scale fishing');
INSERT INTO threat_category (id, description) VALUES (130, '13.5. Pump or substance producing a similar effect');
INSERT INTO threat_category (id, description) VALUES (131, '13.6. chemicals');
INSERT INTO threat_category (id, description) VALUES (132, '13.7. sports');
INSERT INTO threat_category (id, description) VALUES (133, '13.8. other');
INSERT INTO threat_category (id, description) VALUES (134, '14. Other');
INSERT INTO threat_category (id, description) VALUES (135, '15. Unknown threat');

-- Conservation Actions data
INSERT INTO conservation_action_type (id, description) VALUES (1, '0. No Action');
INSERT INTO conservation_action_type (id, description) VALUES (2, '1. Management Plans');
INSERT INTO conservation_action_type (id, description) VALUES (3, '2. Legislation');
INSERT INTO conservation_action_type (id, description) VALUES (4, '3.1. government bodies');
INSERT INTO conservation_action_type (id, description) VALUES (5, '3.2. Resource Management');
INSERT INTO conservation_action_type (id, description) VALUES (6, '3.3. Alternative livelihoods');
INSERT INTO conservation_action_type (id, description) VALUES (7, '4.1. Formal Education');
INSERT INTO conservation_action_type (id, description) VALUES (8, '4.2. awareness');
INSERT INTO conservation_action_type (id, description) VALUES (9, '4.3. Capacity building / training');
INSERT INTO conservation_action_type (id, description) VALUES (10, '4.4. other');
INSERT INTO conservation_action_type (id, description) VALUES (11, '5.1. Taxonomy');
INSERT INTO conservation_action_type (id, description) VALUES (12, '5.2. Population size and geographic distribution');
INSERT INTO conservation_action_type (id, description) VALUES (13, '5.3. Biology and ecology');
INSERT INTO conservation_action_type (id, description) VALUES (14, '5.4. State Habitat');
INSERT INTO conservation_action_type (id, description) VALUES (15, '5.5. threats');
INSERT INTO conservation_action_type (id, description) VALUES (16, '5.6. Use and exploitation');
INSERT INTO conservation_action_type (id, description) VALUES (17, '5.7. Cultural relevance');
INSERT INTO conservation_action_type (id, description) VALUES (18, '5.8. Conservation measures');
INSERT INTO conservation_action_type (id, description) VALUES (19, '5.9. Avalição trends / monitoring');
INSERT INTO conservation_action_type (id, description) VALUES (20, '5.10. other');
INSERT INTO conservation_action_type (id, description) VALUES (21, '6. Maintenance / habitat conservation');
INSERT INTO conservation_action_type (id, description) VALUES (22, '7. Habitat Restoration');
INSERT INTO conservation_action_type (id, description) VALUES (23, '8. Runners');
INSERT INTO conservation_action_type (id, description) VALUES (24, '9. Identification of new Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (25, '10. Protected Areas Establishment');
INSERT INTO conservation_action_type (id, description) VALUES (26, '11. Management of Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (27, '12. Expansion of Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (28, '13. Re-introductions');
INSERT INTO conservation_action_type (id, description) VALUES (29, '14. benign Introductions');
INSERT INTO conservation_action_type (id, description) VALUES (30, '15. Management of hunting / chasing / collection');
INSERT INTO conservation_action_type (id, description) VALUES (31, '16. Trade Management');
INSERT INTO conservation_action_type (id, description) VALUES (32, '17. Restore Management');
INSERT INTO conservation_action_type (id, description) VALUES (33, '18. Management of diseases, pathogens and parasites');
INSERT INTO conservation_action_type (id, description) VALUES (34, '19. Limitation of population growth');
INSERT INTO conservation_action_type (id, description) VALUES (35, '20. Reproduction in captivity / artificial propagation');
INSERT INTO conservation_action_type (id, description) VALUES (36, '21. Genetic Bank');
INSERT INTO conservation_action_type (id, description) VALUES (37, '22. Other');

-- HabitatType data
INSERT INTO habitat_type (id, name) VALUES (1, 'Amazonia - Rain Forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (2, 'Amazonia - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (3, 'Amazonia - Rain Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (4, 'Amazonia - Rain Forest Montana');
INSERT INTO habitat_type (id, name) VALUES (5, 'Amazonia - Rain Forest Open Alluvial');
INSERT INTO habitat_type (id, name) VALUES (6, 'Amazonia - Open Tropical Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (7, 'Amazonia - Rain Forest Open Submontane');
INSERT INTO habitat_type (id, name) VALUES (8, 'Amazonia - Semideciduous forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (9, 'Amazonia - Semideciduous forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (10, 'Amazonia - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (11, 'Amazonia - Deciduous Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (12, 'Amazonia - campinarana Forested');
INSERT INTO habitat_type (id, name) VALUES (13, 'Amazonia - campinarana Tree');
INSERT INTO habitat_type (id, name) VALUES (14, 'Amazonia - campinarana shrub');
INSERT INTO habitat_type (id, name) VALUES (15, 'Amazonia - Campinarana Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (16, 'Amazonia - savannah Woodland');
INSERT INTO habitat_type (id, name) VALUES (17, 'Amazonia - savannah Wooded');
INSERT INTO habitat_type (id, name) VALUES (18, 'Amazonia - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (19, 'Amazonia - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (20, 'Amazonia - Savannah Steppe Forested');
INSERT INTO habitat_type (id, name) VALUES (21, 'Amazonia - Savannah Steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (22, 'Amazonia - Savannah Steppe Park');
INSERT INTO habitat_type (id, name) VALUES (23, 'Amazonia - Savannah Steppe Grassy-woody');
INSERT INTO habitat_type (id, name) VALUES (24, 'Amazonia - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (25, 'Amazonia - Vegetation with Influence fluviomarinha');
INSERT INTO habitat_type (id, name) VALUES (26, 'Amazonia - Vegetation with Fluvial Influence and / or Lakeside');
INSERT INTO habitat_type (id, name) VALUES (27, 'Amazonia - Refuge vegetation Montano');
INSERT INTO habitat_type (id, name) VALUES (28, 'Amazonia - cerradão');
INSERT INTO habitat_type (id, name) VALUES (29, 'Amazonia - Cerrado field');
INSERT INTO habitat_type (id, name) VALUES (30, 'Amazonia - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (31, 'Amazonia - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (32, 'Amazonia - mangrove');
INSERT INTO habitat_type (id, name) VALUES (33, 'Amazonia - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (34, 'Amazonia - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (35, 'Amazonia - Lagos de água doce permanentes');
INSERT INTO habitat_type (id, name) VALUES (36, 'Amazonia - Lagos de água doce sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (37, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas permanentes');
INSERT INTO habitat_type (id, name) VALUES (38, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (39, 'Amazonia - Lagoas / Brejos / Poças permanentes');
INSERT INTO habitat_type (id, name) VALUES (40, 'Amazonia - Lagoas / Brejos / Poças sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (41, 'Amazonia - Lagos salinos, salobros ou alcalinos permanentes');
INSERT INTO habitat_type (id, name) VALUES (42, 'Amazonia - Lagos salinos, salobros ou alcalinos sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (43, 'Amazonia - Nascentes de água ');
INSERT INTO habitat_type (id, name) VALUES (44, 'Amazonia - Carstes e outros sistemas hidrológicos subterrâneos ');
INSERT INTO habitat_type (id, name) VALUES (45, 'Amazonia - Áreas rochosas');
INSERT INTO habitat_type (id, name) VALUES (46, 'Amazonia - Cavernas');
INSERT INTO habitat_type (id, name) VALUES (47, 'Amazonia - Vegetação introduzida');
INSERT INTO habitat_type (id, name) VALUES (48, 'Amazonia - Outros');
INSERT INTO habitat_type (id, name) VALUES (49, 'Mata Atlantica - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (50, 'Mata Atlantica - Rain Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (51, 'Mata Atlantica - Rain Forest Montana');
INSERT INTO habitat_type (id, name) VALUES (52, 'Mata Atlantica - Open Tropical Rain Forest');
INSERT INTO habitat_type (id, name) VALUES (53, 'Mata Atlantica - Rain Forest Mista Montana');
INSERT INTO habitat_type (id, name) VALUES (54, 'Mata Atlantica - Rain Forest Mixed Alto Montana');
INSERT INTO habitat_type (id, name) VALUES (55, 'Mata Atlantica - Semideciduous forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (56, 'Mata Atlantica - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (57, 'Mata Atlantica - Semideciduous forest Montana');
INSERT INTO habitat_type (id, name) VALUES (58, 'Mata Atlantica - Deciduous Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (59, 'Mata Atlantica - steppe Park');
INSERT INTO habitat_type (id, name) VALUES (60, 'Mata Atlantica - Steppe Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (61, 'Mata Atlantica - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (62, 'Mata Atlantica - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (63, 'Mata Atlantica - Savannah Steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (64, 'Mata Atlantica - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (65, 'Mata Atlantica - Vegetation with Influence fluviomarinha');
INSERT INTO habitat_type (id, name) VALUES (66, 'Mata Atlantica - Vegetation with Fluvial Influence and / or Lakeside');
INSERT INTO habitat_type (id, name) VALUES (67, 'Mata Atlantica - Refuge vegetation Montano');
INSERT INTO habitat_type (id, name) VALUES (68, 'Mata Atlantica - Refuge vegetation High Montano');
INSERT INTO habitat_type (id, name) VALUES (69, 'Mata Atlantica - rock fields');
INSERT INTO habitat_type (id, name) VALUES (70, 'Mata Atlantica - Altitude fields');
INSERT INTO habitat_type (id, name) VALUES (71, 'Mata Atlantica - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (72, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (73, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (74, 'Mata Atlantica - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (75, 'Mata Atlantica - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (76, 'Mata Atlantica - Open Tropical Rain Forest');
INSERT INTO habitat_type (id, name) VALUES (77, 'Mata Atlantica - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (78, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (79, 'Mata Atlantica - mangrove');
INSERT INTO habitat_type (id, name) VALUES (80, 'Mata Atlantica - Restinga');
INSERT INTO habitat_type (id, name) VALUES (81, 'Mata Atlantica - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (82, 'Mata Atlantica - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (83, 'Mata Atlantica - Freshwater lakes permanent');
INSERT INTO habitat_type (id, name) VALUES (84, 'Mata Atlantica - Freshwater lakes seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (85, 'Mata Atlantica - Ponds / Wetlands / Puddles saline, brackish or alkaline permanent');
INSERT INTO habitat_type (id, name) VALUES (86, 'Mata Atlantica - caves');
INSERT INTO habitat_type (id, name) VALUES (87, 'Mata Atlantica - Ponds / Wetlands / Pools permanent');
INSERT INTO habitat_type (id, name) VALUES (88, 'Mata Atlantica - Ponds / Wetlands / Pools seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (89, 'Mata Atlantica - Lakes saline, brackish or alkaline permanent');
INSERT INTO habitat_type (id, name) VALUES (90, 'Mata Atlantica - Lakes saline, brackish or alkaline seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (91, 'Mata Atlantica - Water sources');
INSERT INTO habitat_type (id, name) VALUES (92, 'Mata Atlantica - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (93, 'Mata Atlantica - rocky areas');
INSERT INTO habitat_type (id, name) VALUES (94, 'Mata Atlantica - caves');
INSERT INTO habitat_type (id, name) VALUES (95, 'Mata Atlantica - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (96, 'Mata Atlantica - other');
