BEGIN;

-- ExtinctionRiskConfiguration data
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (1, 'CRITICALLY_ENDANGERED', 1, 250, 50, 50, 10, 100, 90, 90.0, 80.0, 50.0);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (2, 'ENDANGERED', 5, 2500, 250, 250, 5000, 500, 250, 70.0, 50.0, 20.0);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (3, 'VUNERABLE', 10, 10000, 1000, 1000, 20000, 2000, 1000, 50.0, 30.0, 10.0);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (4, 'EXTINCT', null, null, null, null, null, null, null, null, null, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (5, 'DATA_DEFICIENT', null, null, null, null, null, null, null, null, null, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (6, 'LEAST_CONCERN', null, null, null, null, null, null, null, null, null, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (7, 'NOT_APPLICABLE', null, null, null, null, null, null, null, null, null, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (8, 'NEAR_THREATENED', 10, 10000, 1000, null, 2000, 20000, null, 40.0, 20.0, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (9, 'EXTINCT_IN_THE_WILD', null, null, null, null, null, null, null, null, null, null);
INSERT INTO extinction_risk_configuration (id, category, b2a_number_of_locations, c_number_of_mature_individuals, d_number_of_mature_individuals, c2a_number_of_mature_individuals_in_sub, b2_area_of_ocuppancy, b1_extent_of_occurrence, c2a_perc_mature_individuals_one_sub, a1_perc_population_decline, a2_perc_population_decline, e_prob_extinction_in_the_wild) VALUES (10, 'REGIONALLY_EXTINCT', null, null, null, null, null, null, null, null, null, null);

-- IntegrationSource data
INSERT INTO integration_source (id, source, name) VALUES (1, 'FLORA', 'JBRJ IPT - Flora');
INSERT INTO integration_source (id, source, name) VALUES (2, 'SPECIES_PLUS', 'WCMC SP+');
INSERT INTO integration_source (id, source, name) VALUES (3, 'FAUNA', 'JBRJ IPT - Fauna');

-- Country data
INSERT INTO country (id, name) VALUES (1, 'Brazil');

-- State data
INSERT INTO state (id, name, country_id, code) VALUES (1, 'Acre', 1, 'AC');
INSERT INTO state (id, name, country_id, code) VALUES (2, 'Alagoas', 1, 'AL');
INSERT INTO state (id, name, country_id, code) VALUES (3, 'Amapá', 1, 'AP');
INSERT INTO state (id, name, country_id, code) VALUES (4, 'Amazonas', 1, 'AM');
INSERT INTO state (id, name, country_id, code) VALUES (5, 'Bahia', 1, 'BA');
INSERT INTO state (id, name, country_id, code) VALUES (6, 'Ceará', 1, 'CE');
INSERT INTO state (id, name, country_id, code) VALUES (7, 'Distrito Federal', 1, 'DF');
INSERT INTO state (id, name, country_id, code) VALUES (8, 'Espírito Santo', 1, 'ES');
INSERT INTO state (id, name, country_id, code) VALUES (9, 'Goiás', 1, 'GO');
INSERT INTO state (id, name, country_id, code) VALUES (10, 'Maranhão', 1, 'MA');
INSERT INTO state (id, name, country_id, code) VALUES (11, 'Mato Grosso', 1, 'MT');
INSERT INTO state (id, name, country_id, code) VALUES (12, 'Mato Grosso do Sul', 1, 'MS');
INSERT INTO state (id, name, country_id, code) VALUES (13, 'Minas Gerais', 1, 'MG');
INSERT INTO state (id, name, country_id, code) VALUES (14, 'Pará', 1, 'PA');
INSERT INTO state (id, name, country_id, code) VALUES (15, 'Paraíba', 1, 'PB');
INSERT INTO state (id, name, country_id, code) VALUES (16, 'Paraná', 1, 'PR');
INSERT INTO state (id, name, country_id, code) VALUES (17, 'Pernambuco', 1, 'PE');
INSERT INTO state (id, name, country_id, code) VALUES (18, 'Piauí', 1, 'PI');
INSERT INTO state (id, name, country_id, code) VALUES (19, 'Rio de Janeiro', 1, 'RJ');
INSERT INTO state (id, name, country_id, code) VALUES (20, 'Rio Grande do Norte', 1, 'RN');
INSERT INTO state (id, name, country_id, code) VALUES (21, 'Rio Grande do Sul', 1, 'RS');
INSERT INTO state (id, name, country_id, code) VALUES (22, 'Rondônia', 1, 'RO');
INSERT INTO state (id, name, country_id, code) VALUES (23, 'Roraima', 1, 'RR');
INSERT INTO state (id, name, country_id, code) VALUES (24, 'Santa Catarina', 1, 'SC');
INSERT INTO state (id, name, country_id, code) VALUES (25, 'São Paulo', 1, 'SP');
INSERT INTO state (id, name, country_id, code) VALUES (26, 'Sergipe', 1, 'SE');
INSERT INTO state (id, name, country_id, code) VALUES (27, 'Tocantins', 1, 'TO');

-- Threats data
INSERT INTO threat_category (id, description) VALUES (1, '0. No threat');
INSERT INTO threat_category (id, description) VALUES (2, '1.1. Agriculture rotation');
INSERT INTO threat_category (id, description) VALUES (3, '1.2. Small farms');
INSERT INTO threat_category (id, description) VALUES (4, '1.3. Agro-industrial agriculture');
INSERT INTO threat_category (id, description) VALUES (5, '1.4. Planting for logging on a small scale');
INSERT INTO threat_category (id, description) VALUES (6, '1.5. Planting for logging on a large scale');
INSERT INTO threat_category (id, description) VALUES (7, '1.6. Nomadic livestock');
INSERT INTO threat_category (id, description) VALUES (8, '1.7. Farming Small Properties');
INSERT INTO threat_category (id, description) VALUES (9, '1.8. Agro-industry Livestock');
INSERT INTO threat_category (id, description) VALUES (10, '1.9. marine aquaculture');
INSERT INTO threat_category (id, description) VALUES (11, '1.10. Freshwater Aquaculture');
INSERT INTO threat_category (id, description) VALUES (12, '2.1. Sand extraction');
INSERT INTO threat_category (id, description) VALUES (13, '2.2. Pebble extraction / stone');
INSERT INTO threat_category (id, description) VALUES (14, '2.3. Mineral extraction - underground');
INSERT INTO threat_category (id, description) VALUES (15, '2.4. Mineral extraction - mining');
INSERT INTO threat_category (id, description) VALUES (16, '2.5. Extraction of oil / oil');
INSERT INTO threat_category (id, description) VALUES (17, '2.6. Natural gas extraction');
INSERT INTO threat_category (id, description) VALUES (18, '2.7. Groundwater extraction');
INSERT INTO threat_category (id, description) VALUES (19, '3.1. Logging Subsistence / small scale');
INSERT INTO threat_category (id, description) VALUES (20, '3.2. Wood selective logging extraction');
INSERT INTO threat_category (id, description) VALUES (21, '3.3. Logging / deforestation');
INSERT INTO threat_category (id, description) VALUES (22, '3.4. Extraction of timber / wood for charcoal');
INSERT INTO threat_category (id, description) VALUES (23, '3.5. Not woody vegetation collection');
INSERT INTO threat_category (id, description) VALUES (24, '4.1.1. Industry Installation');
INSERT INTO threat_category (id, description) VALUES (25, '4.1.2. Working Industry');
INSERT INTO threat_category (id, description) VALUES (26, '4.2.1. Installation and operation of roads');
INSERT INTO threat_category (id, description) VALUES (27, '4.2.2. Installation and operation of railways');
INSERT INTO threat_category (id, description) VALUES (28, '4.2.3. Installation and operation of airports');
INSERT INTO threat_category (id, description) VALUES (29, '4.2.4. Installation and operation of ports and waterways');
INSERT INTO threat_category (id, description) VALUES (30, '4.3.1. Hydroelectric Power Plant (HPP)');
INSERT INTO threat_category (id, description) VALUES (31, '4.3.2. Small Hydroelectric Plant (SHP)');
INSERT INTO threat_category (id, description) VALUES (32, '4.3.3. Central Hydroelectric Generation (CGH)');
INSERT INTO threat_category (id, description) VALUES (33, '4.3.4. wind farm');
INSERT INTO threat_category (id, description) VALUES (34, '4.3.5. nuclear plant');
INSERT INTO threat_category (id, description) VALUES (35, '4.3.6. Power lines installation');
INSERT INTO threat_category (id, description) VALUES (36, '4.4. Infrastructure installation Tourism / recreation');
INSERT INTO threat_category (id, description) VALUES (37, '4.5. Telecommunications infrastructure installation');
INSERT INTO threat_category (id, description) VALUES (38, '4.6. Construction of dams / reservoirs to supply');
INSERT INTO threat_category (id, description) VALUES (39, '5.1. Rural settlements');
INSERT INTO threat_category (id, description) VALUES (40, '5.2. Boom towns');
INSERT INTO threat_category (id, description) VALUES (41, '6.1. Burned');
INSERT INTO threat_category (id, description) VALUES (42, '6.2. Natural origin of fire');
INSERT INTO threat_category (id, description) VALUES (43, '7.1. Introduction of exotic species (direct impact on the habitat)');
INSERT INTO threat_category (id, description) VALUES (44, '7.2. Competitors');
INSERT INTO threat_category (id, description) VALUES (45, '7.3. Predators');
INSERT INTO threat_category (id, description) VALUES (46, '7.4. Hybridization');
INSERT INTO threat_category (id, description) VALUES (47, '7.5. Pathogens / parasites');
INSERT INTO threat_category (id, description) VALUES (48, '7.6. Contact domestic species');
INSERT INTO threat_category (id, description) VALUES (49, '7.7. Other');
INSERT INTO threat_category (id, description) VALUES (50, '8.1. Use subsistence / local barter');
INSERT INTO threat_category (id, description) VALUES (51, '8.2. Sports');
INSERT INTO threat_category (id, description) VALUES (52, '8.3. Commercial');
INSERT INTO threat_category (id, description) VALUES (53, '8.4. Scientific collection');
INSERT INTO threat_category (id, description) VALUES (54, '8.5. Pest control');
INSERT INTO threat_category (id, description) VALUES (55, '8.6. Coral removal');
INSERT INTO threat_category (id, description) VALUES (56, '8.7. Other');
INSERT INTO threat_category (id, description) VALUES (57, '9.1. Running over');
INSERT INTO threat_category (id, description) VALUES (58, '9.2. Collisions Torres and Buildings');
INSERT INTO threat_category (id, description) VALUES (59, '9.3. Poisoning');
INSERT INTO threat_category (id, description) VALUES (60, '9.4. Other');
INSERT INTO threat_category (id, description) VALUES (61, '10.1. Global / ocean warming');
INSERT INTO threat_category (id, description) VALUES (62, '10.2. Acid rain');
INSERT INTO threat_category (id, description) VALUES (63, '10.3. Effects of the holes in the ozone layer');
INSERT INTO threat_category (id, description) VALUES (64, '10.4. Smoke');
INSERT INTO threat_category (id, description) VALUES (65, '10.5. Soil pollution - origin in agriculture');
INSERT INTO threat_category (id, description) VALUES (66, '10.6. Soil pollution - domestic origin');
INSERT INTO threat_category (id, description) VALUES (67, '10.7. Soil pollution - Source Commercial / Industrial');
INSERT INTO threat_category (id, description) VALUES (68, '10.8. Light pollution');
INSERT INTO threat_category (id, description) VALUES (69, '10.9. Noise pollution');
INSERT INTO threat_category (id, description) VALUES (70, '10.10. Water pollution - agricultural sources');
INSERT INTO threat_category (id, description) VALUES (71, '10:11. Water pollution - domestic origin');
INSERT INTO threat_category (id, description) VALUES (72, '10:12. Water pollution - commercial origin / Industrial');
INSERT INTO threat_category (id, description) VALUES (73, '10:13. Thermal pollution');
INSERT INTO threat_category (id, description) VALUES (74, '10:14. Oil spill');
INSERT INTO threat_category (id, description) VALUES (75, '10:15. Siltation');
INSERT INTO threat_category (id, description) VALUES (76, '10:16. Dump waste / sewage - source in the city');
INSERT INTO threat_category (id, description) VALUES (77, '10:16. Dump waste / sewage - source in the industry');
INSERT INTO threat_category (id, description) VALUES (78, '10:17. Disposal of solid waste - originated in the city');
INSERT INTO threat_category (id, description) VALUES (79, '10:17. Disposal of solid waste - source in the industry');
INSERT INTO threat_category (id, description) VALUES (80, '10:18. Noise pollution of waters');
INSERT INTO threat_category (id, description) VALUES (81, '10:19. Other');
INSERT INTO threat_category (id, description) VALUES (82, '11.1. Drought');
INSERT INTO threat_category (id, description) VALUES (83, '11.2. Storms / floods');
INSERT INTO threat_category (id, description) VALUES (84, '11.3. Thermal extremes');
INSERT INTO threat_category (id, description) VALUES (85, '11.4. Landslides');
INSERT INTO threat_category (id, description) VALUES (86, '11.5. Other');
INSERT INTO threat_category (id, description) VALUES (87, '12.1. Competitors');
INSERT INTO threat_category (id, description) VALUES (88, '12.2. Predators');
INSERT INTO threat_category (id, description) VALUES (89, '12.3. Prey / food base');
INSERT INTO threat_category (id, description) VALUES (90, '12.4. Hybridization');
INSERT INTO threat_category (id, description) VALUES (91, '12.5. Pathogens / parasites');
INSERT INTO threat_category (id, description) VALUES (92, '12.6. Other');
INSERT INTO threat_category (id, description) VALUES (93, '13.1.1. Surface longline');
INSERT INTO threat_category (id, description) VALUES (94, '13.1.2. Bottom longline');
INSERT INTO threat_category (id, description) VALUES (95, '13.1.3. Hand line');
INSERT INTO threat_category (id, description) VALUES (96, '13.1.4. Coastal gill surface');
INSERT INTO threat_category (id, description) VALUES (97, '13.1.5. Coastal gill background');
INSERT INTO threat_category (id, description) VALUES (98, '13.1.6. Oceanic gill surface');
INSERT INTO threat_category (id, description) VALUES (99, '13.1.7. Oceanic driftnet background');
INSERT INTO threat_category (id, description) VALUES (100, '13.1.8. Bottom trawling');
INSERT INTO threat_category (id, description) VALUES (101, '13.1.9. Coastal trawl double bottom');
INSERT INTO threat_category (id, description) VALUES (102, '13.1.10. Ocean trawl background (single and double)');
INSERT INTO threat_category (id, description) VALUES (103, '01.13.11. Drag (half water)');
INSERT INTO threat_category (id, description) VALUES (104, '01.13.12. siege');
INSERT INTO threat_category (id, description) VALUES (105, '13.1.13. creels');
INSERT INTO threat_category (id, description) VALUES (106, '13.01.14. puçá');
INSERT INTO threat_category (id, description) VALUES (107, '13.1.15. Underwater manual collection');
INSERT INTO threat_category (id, description) VALUES (108, '13.01.16. other');
INSERT INTO threat_category (id, description) VALUES (109, '13.2.1. single line');
INSERT INTO threat_category (id, description) VALUES (110, '13.2.2. paternoster');
INSERT INTO threat_category (id, description) VALUES (111, '13.2.3. Seine');
INSERT INTO threat_category (id, description) VALUES (112, '13.2.4. Drift Network');
INSERT INTO threat_category (id, description) VALUES (113, '13.2.5. Gill net (gillnets)');
INSERT INTO threat_category (id, description) VALUES (114, '13.2.6. drag');
INSERT INTO threat_category (id, description) VALUES (115, '13.2.7. flue');
INSERT INTO threat_category (id, description) VALUES (116, '13.2.8. hook');
INSERT INTO threat_category (id, description) VALUES (117, '13.2.9. harpoon');
INSERT INTO threat_category (id, description) VALUES (118, '13.2.10. corral');
INSERT INTO threat_category (id, description) VALUES (119, '13.2.11. Archery');
INSERT INTO threat_category (id, description) VALUES (120, '13.2.12. Puça');
INSERT INTO threat_category (id, description) VALUES (121, '13.2.13. underwater');
INSERT INTO threat_category (id, description) VALUES (122, '13.02.14. of Trolling');
INSERT INTO threat_category (id, description) VALUES (123, '13.02.15. Barranco');
INSERT INTO threat_category (id, description) VALUES (124, '13.2.16. with Fly');
INSERT INTO threat_category (id, description) VALUES (125, '13.2.17. Beach');
INSERT INTO threat_category (id, description) VALUES (126, '13.2.18. Round');
INSERT INTO threat_category (id, description) VALUES (127, '13.2.19. other');
INSERT INTO threat_category (id, description) VALUES (128, '13.3. Industrial fishing');
INSERT INTO threat_category (id, description) VALUES (129, '13.4. Small-scale fishing');
INSERT INTO threat_category (id, description) VALUES (130, '13.5. Pump or substance producing a similar effect');
INSERT INTO threat_category (id, description) VALUES (131, '13.6. chemicals');
INSERT INTO threat_category (id, description) VALUES (132, '13.7. sports');
INSERT INTO threat_category (id, description) VALUES (133, '13.8. other');
INSERT INTO threat_category (id, description) VALUES (134, '14. Other');
INSERT INTO threat_category (id, description) VALUES (135, '15. Unknown threat');

-- Conservation Actions data
INSERT INTO conservation_action_type (id, description) VALUES (1, '0. No Action');
INSERT INTO conservation_action_type (id, description) VALUES (2, '1. Management Plans');
INSERT INTO conservation_action_type (id, description) VALUES (3, '2. Legislation');
INSERT INTO conservation_action_type (id, description) VALUES (4, '3.1. government bodies');
INSERT INTO conservation_action_type (id, description) VALUES (5, '3.2. Resource Management');
INSERT INTO conservation_action_type (id, description) VALUES (6, '3.3. Alternative livelihoods');
INSERT INTO conservation_action_type (id, description) VALUES (7, '4.1. Formal Education');
INSERT INTO conservation_action_type (id, description) VALUES (8, '4.2. awareness');
INSERT INTO conservation_action_type (id, description) VALUES (9, '4.3. Capacity building / training');
INSERT INTO conservation_action_type (id, description) VALUES (10, '4.4. other');
INSERT INTO conservation_action_type (id, description) VALUES (11, '5.1. Taxonomy');
INSERT INTO conservation_action_type (id, description) VALUES (12, '5.2. Population size and geographic distribution');
INSERT INTO conservation_action_type (id, description) VALUES (13, '5.3. Biology and ecology');
INSERT INTO conservation_action_type (id, description) VALUES (14, '5.4. State Habitat');
INSERT INTO conservation_action_type (id, description) VALUES (15, '5.5. threats');
INSERT INTO conservation_action_type (id, description) VALUES (16, '5.6. Use and exploitation');
INSERT INTO conservation_action_type (id, description) VALUES (17, '5.7. Cultural relevance');
INSERT INTO conservation_action_type (id, description) VALUES (18, '5.8. Conservation measures');
INSERT INTO conservation_action_type (id, description) VALUES (19, '5.9. Avalição trends / monitoring');
INSERT INTO conservation_action_type (id, description) VALUES (20, '5.10. other');
INSERT INTO conservation_action_type (id, description) VALUES (21, '6. Maintenance / habitat conservation');
INSERT INTO conservation_action_type (id, description) VALUES (22, '7. Habitat Restoration');
INSERT INTO conservation_action_type (id, description) VALUES (23, '8. Runners');
INSERT INTO conservation_action_type (id, description) VALUES (24, '9. Identification of new Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (25, '10. Protected Areas Establishment');
INSERT INTO conservation_action_type (id, description) VALUES (26, '11. Management of Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (27, '12. Expansion of Protected Areas');
INSERT INTO conservation_action_type (id, description) VALUES (28, '13. Re-introductions');
INSERT INTO conservation_action_type (id, description) VALUES (29, '14. benign Introductions');
INSERT INTO conservation_action_type (id, description) VALUES (30, '15. Management of hunting / chasing / collection');
INSERT INTO conservation_action_type (id, description) VALUES (31, '16. Trade Management');
INSERT INTO conservation_action_type (id, description) VALUES (32, '17. Restore Management');
INSERT INTO conservation_action_type (id, description) VALUES (33, '18. Management of diseases, pathogens and parasites');
INSERT INTO conservation_action_type (id, description) VALUES (34, '19. Limitation of population growth');
INSERT INTO conservation_action_type (id, description) VALUES (35, '20. Reproduction in captivity / artificial propagation');
INSERT INTO conservation_action_type (id, description) VALUES (36, '21. Genetic Bank');
INSERT INTO conservation_action_type (id, description) VALUES (37, '22. Other');

-- HabitatType data
INSERT INTO habitat_type (id, name) VALUES (1, 'Amazonia - Rain Forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (2, 'Amazonia - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (3, 'Amazonia - Rain Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (4, 'Amazonia - Rain Forest Montana');
INSERT INTO habitat_type (id, name) VALUES (5, 'Amazonia - Rain Forest Open Alluvial');
INSERT INTO habitat_type (id, name) VALUES (6, 'Amazonia - Open Tropical Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (7, 'Amazonia - Rain Forest Open Submontane');
INSERT INTO habitat_type (id, name) VALUES (8, 'Amazonia - Semideciduous forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (9, 'Amazonia - Semideciduous forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (10, 'Amazonia - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (11, 'Amazonia - Deciduous Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (12, 'Amazonia - campinarana Forested');
INSERT INTO habitat_type (id, name) VALUES (13, 'Amazonia - campinarana Tree');
INSERT INTO habitat_type (id, name) VALUES (14, 'Amazonia - campinarana shrub');
INSERT INTO habitat_type (id, name) VALUES (15, 'Amazonia - Campinarana Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (16, 'Amazonia - savannah Woodland');
INSERT INTO habitat_type (id, name) VALUES (17, 'Amazonia - savannah Wooded');
INSERT INTO habitat_type (id, name) VALUES (18, 'Amazonia - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (19, 'Amazonia - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (20, 'Amazonia - Savannah Steppe Forested');
INSERT INTO habitat_type (id, name) VALUES (21, 'Amazonia - Savannah Steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (22, 'Amazonia - Savannah Steppe Park');
INSERT INTO habitat_type (id, name) VALUES (23, 'Amazonia - Savannah Steppe Grassy-woody');
INSERT INTO habitat_type (id, name) VALUES (24, 'Amazonia - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (25, 'Amazonia - Vegetation with Influence fluviomarinha');
INSERT INTO habitat_type (id, name) VALUES (26, 'Amazonia - Vegetation with Fluvial Influence and / or Lakeside');
INSERT INTO habitat_type (id, name) VALUES (27, 'Amazonia - Refuge vegetation Montano');
INSERT INTO habitat_type (id, name) VALUES (28, 'Amazonia - cerradão');
INSERT INTO habitat_type (id, name) VALUES (29, 'Amazonia - Cerrado field');
INSERT INTO habitat_type (id, name) VALUES (30, 'Amazonia - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (31, 'Amazonia - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (32, 'Amazonia - mangrove');
INSERT INTO habitat_type (id, name) VALUES (33, 'Amazonia - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (34, 'Amazonia - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (35, 'Amazonia - Lagos de água doce permanentes');
INSERT INTO habitat_type (id, name) VALUES (36, 'Amazonia - Lagos de água doce sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (37, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas permanentes');
INSERT INTO habitat_type (id, name) VALUES (38, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (39, 'Amazonia - Lagoas / Brejos / Poças permanentes');
INSERT INTO habitat_type (id, name) VALUES (40, 'Amazonia - Lagoas / Brejos / Poças sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (41, 'Amazonia - Lagos salinos, salobros ou alcalinos permanentes');
INSERT INTO habitat_type (id, name) VALUES (42, 'Amazonia - Lagos salinos, salobros ou alcalinos sazonais/intermitentes');
INSERT INTO habitat_type (id, name) VALUES (43, 'Amazonia - Nascentes de água ');
INSERT INTO habitat_type (id, name) VALUES (44, 'Amazonia - Carstes e outros sistemas hidrológicos subterrâneos ');
INSERT INTO habitat_type (id, name) VALUES (45, 'Amazonia - Áreas rochosas');
INSERT INTO habitat_type (id, name) VALUES (46, 'Amazonia - Cavernas');
INSERT INTO habitat_type (id, name) VALUES (47, 'Amazonia - Vegetação introduzida');
INSERT INTO habitat_type (id, name) VALUES (48, 'Amazonia - Outros');
INSERT INTO habitat_type (id, name) VALUES (49, 'Mata Atlantica - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (50, 'Mata Atlantica - Rain Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (51, 'Mata Atlantica - Rain Forest Montana');
INSERT INTO habitat_type (id, name) VALUES (52, 'Mata Atlantica - Open Tropical Rain Forest');
INSERT INTO habitat_type (id, name) VALUES (53, 'Mata Atlantica - Rain Forest Mista Montana');
INSERT INTO habitat_type (id, name) VALUES (54, 'Mata Atlantica - Rain Forest Mixed Alto Montana');
INSERT INTO habitat_type (id, name) VALUES (55, 'Mata Atlantica - Semideciduous forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (56, 'Mata Atlantica - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (57, 'Mata Atlantica - Semideciduous forest Montana');
INSERT INTO habitat_type (id, name) VALUES (58, 'Mata Atlantica - Deciduous Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (59, 'Mata Atlantica - steppe Park');
INSERT INTO habitat_type (id, name) VALUES (60, 'Mata Atlantica - Steppe Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (61, 'Mata Atlantica - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (62, 'Mata Atlantica - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (63, 'Mata Atlantica - Savannah Steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (64, 'Mata Atlantica - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (65, 'Mata Atlantica - Vegetation with Influence fluviomarinha');
INSERT INTO habitat_type (id, name) VALUES (66, 'Mata Atlantica - Vegetation with Fluvial Influence and / or Lakeside');
INSERT INTO habitat_type (id, name) VALUES (67, 'Mata Atlantica - Refuge vegetation Montano');
INSERT INTO habitat_type (id, name) VALUES (68, 'Mata Atlantica - Refuge vegetation High Montano');
INSERT INTO habitat_type (id, name) VALUES (69, 'Mata Atlantica - rock fields');
INSERT INTO habitat_type (id, name) VALUES (70, 'Mata Atlantica - Altitude fields');
INSERT INTO habitat_type (id, name) VALUES (71, 'Mata Atlantica - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (72, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (73, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (74, 'Mata Atlantica - Semideciduous forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (75, 'Mata Atlantica - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (76, 'Mata Atlantica - Open Tropical Rain Forest');
INSERT INTO habitat_type (id, name) VALUES (77, 'Mata Atlantica - Rain Forest of the Lowlands');
INSERT INTO habitat_type (id, name) VALUES (78, 'Mata Atlantica - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (79, 'Mata Atlantica - mangrove');
INSERT INTO habitat_type (id, name) VALUES (80, 'Mata Atlantica - Restinga');
INSERT INTO habitat_type (id, name) VALUES (81, 'Mata Atlantica - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (82, 'Mata Atlantica - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (83, 'Mata Atlantica - Freshwater lakes permanent');
INSERT INTO habitat_type (id, name) VALUES (84, 'Mata Atlantica - Freshwater lakes seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (85, 'Mata Atlantica - Ponds / Wetlands / Puddles saline, brackish or alkaline permanent');
INSERT INTO habitat_type (id, name) VALUES (86, 'Mata Atlantica - caves');
INSERT INTO habitat_type (id, name) VALUES (87, 'Mata Atlantica - Ponds / Wetlands / Pools permanent');
INSERT INTO habitat_type (id, name) VALUES (88, 'Mata Atlantica - Ponds / Wetlands / Pools seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (89, 'Mata Atlantica - Lakes saline, brackish or alkaline permanent');
INSERT INTO habitat_type (id, name) VALUES (90, 'Mata Atlantica - Lakes saline, brackish or alkaline seasonal/intermittent');
INSERT INTO habitat_type (id, name) VALUES (91, 'Mata Atlantica - Water sources');
INSERT INTO habitat_type (id, name) VALUES (92, 'Mata Atlantica - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (93, 'Mata Atlantica - rocky areas');
INSERT INTO habitat_type (id, name) VALUES (94, 'Mata Atlantica - caves');
INSERT INTO habitat_type (id, name) VALUES (95, 'Mata Atlantica - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (96, 'Mata Atlantica - other');
INSERT INTO habitat_type (id, name) VALUES (97, 'Closed - savanna Woodland');
INSERT INTO habitat_type (id, name) VALUES (98, 'Closed - savanna Wooded');
INSERT INTO habitat_type (id, name) VALUES (99, 'Closed - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (100, 'Closed - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (101, 'Closed - Semideciduous forest');
INSERT INTO habitat_type (id, name) VALUES (102, 'Closed - Deciduous Forest');
INSERT INTO habitat_type (id, name) VALUES (103, 'Closed - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (104, 'Closed - Vegetation with Influence fluviomarinha');
INSERT INTO habitat_type (id, name) VALUES (105, 'Closed - Refuge vegetation Montano');
INSERT INTO habitat_type (id, name) VALUES (106, 'Closed - Rupestres fields');
INSERT INTO habitat_type (id, name) VALUES (107, 'Closed - closed');
INSERT INTO habitat_type (id, name) VALUES (108, 'Closed - Cerrado field');
INSERT INTO habitat_type (id, name) VALUES (109, 'Closed - Campo Sujo');
INSERT INTO habitat_type (id, name) VALUES (110, 'Closed - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (111, 'Closed - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (112, 'Closed - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (113, 'Closed - Freshwater lakes permanent');
INSERT INTO habitat_type (id, name) VALUES (114, 'Closed - Freshwater lakes Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (115, 'Closed - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (116, 'Closed - Ponds / Wetlands / Puddles saline, brackish or alkaline Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (117, 'Closed - Ponds / Wetlands / Pools Permanentes');
INSERT INTO habitat_type (id, name) VALUES (118, 'Closed - Ponds / Wetlands / Pools Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (119, 'Closed - Lakes saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (120, 'Closed - Lakes saline, brackish or alkaline Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (121, 'Closed - Water sources');
INSERT INTO habitat_type (id, name) VALUES (122, 'Closed - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (123, 'Closed - Cavernas');
INSERT INTO habitat_type (id, name) VALUES (124, 'Closed - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (125, 'Closed - Other');
INSERT INTO habitat_type (id, name) VALUES (126, 'Caatinga - Freshwater lakes permanent');
INSERT INTO habitat_type (id, name) VALUES (127, 'Caatinga - Freshwater lakes Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (128, 'Caatinga - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (129, 'Caatinga - Ponds / Wetlands / Puddles saline, brackish or alkaline Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (130, 'Caatinga - Ponds / Wetlands / Pools Permanentes');
INSERT INTO habitat_type (id, name) VALUES (131, 'Caatinga - Ponds / Wetlands / Pools Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (132, 'Caatinga - Lakes saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (133, 'Caatinga - Lakes saline, brackish or alkaline Seasonal / Intermittent');
INSERT INTO habitat_type (id, name) VALUES (134, 'Caatinga - Water sources');
INSERT INTO habitat_type (id, name) VALUES (135, 'Caatinga - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (136, 'Caatinga - caves');
INSERT INTO habitat_type (id, name) VALUES (137, 'Caatinga - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (138, 'Caatinga - Other');
INSERT INTO habitat_type (id, name) VALUES (139, 'Pampa - steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (140, 'Pampa - steppe Park');
INSERT INTO habitat_type (id, name) VALUES (141, 'Pampa - Steppe Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (142, 'Pampa - Savannah Steppe Park');
INSERT INTO habitat_type (id, name) VALUES (143, 'Pampa - Semideciduous forest');
INSERT INTO habitat_type (id, name) VALUES (144, 'Pampa - Vegetation with Marine Influence');
INSERT INTO habitat_type (id, name) VALUES (145, 'Pampa - Sulinos fields');
INSERT INTO habitat_type (id, name) VALUES (146, 'Pampa - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (147, 'Pampa - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (148, 'Pampa - Freshwater lakes Permanentes');
INSERT INTO habitat_type (id, name) VALUES (149, 'Pampa - Freshwater lakes Sazonais/Intermitentes');
INSERT INTO habitat_type (id, name) VALUES (150, 'Pampa - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (151, 'Pampa - Ponds / Wetlands / Puddles saline, brackish or alkaline Sazonais/Intermitentes');
INSERT INTO habitat_type (id, name) VALUES (152, 'Pampa - Ponds / Wetlands / Pools Permanentes');
INSERT INTO habitat_type (id, name) VALUES (153, 'Pampa - Ponds / Wetlands / Pools Sazonais/Intermitentes');
INSERT INTO habitat_type (id, name) VALUES (154, 'Pampa - Lakes saline, brackish or alkaline Permanentes');
INSERT INTO habitat_type (id, name) VALUES (155, 'Pampa - Lakes saline, brackish or alkaline Sazonais/Intermitentes');
INSERT INTO habitat_type (id, name) VALUES (156, 'Pampa - Water sources');
INSERT INTO habitat_type (id, name) VALUES (157, 'Pampa - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (158, 'Pampa - rocky areas');
INSERT INTO habitat_type (id, name) VALUES (159, 'Pampa - Caverns');
INSERT INTO habitat_type (id, name) VALUES (160, 'Pampa - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (161, 'Pampa - Other');
INSERT INTO habitat_type (id, name) VALUES (162, 'Swamp - Semideciduous forest Alluvial');
INSERT INTO habitat_type (id, name) VALUES (163, 'Swamp - Deciduous Forest of Lowlands');
INSERT INTO habitat_type (id, name) VALUES (164, 'Swamp - Deciduous Forest Submontane');
INSERT INTO habitat_type (id, name) VALUES (165, 'Swamp - savanna Woodland');
INSERT INTO habitat_type (id, name) VALUES (166, 'Swamp - savana Wooded');
INSERT INTO habitat_type (id, name) VALUES (167, 'Swamp - savannah Park');
INSERT INTO habitat_type (id, name) VALUES (168, 'Swamp - Savannah Grassy-Woody');
INSERT INTO habitat_type (id, name) VALUES (169, 'Swamp - Savannah Steppe Forested');
INSERT INTO habitat_type (id, name) VALUES (170, 'Swamp - Savannah Steppe Tree');
INSERT INTO habitat_type (id, name) VALUES (171, 'Swamp - Savannah Steppe Park');
INSERT INTO habitat_type (id, name) VALUES (172, 'Swamp - Savannah Steppe Park');
INSERT INTO habitat_type (id, name) VALUES (173, 'Swamp - Cerradão');
INSERT INTO habitat_type (id, name) VALUES (174, 'Swamp - Cerrado field');
INSERT INTO habitat_type (id, name) VALUES (175, 'Swamp - field Dirty');
INSERT INTO habitat_type (id, name) VALUES (176, 'Swamp - Campo Limpo');
INSERT INTO habitat_type (id, name) VALUES (177, 'Swamp - Rivers, streams, rapids and waterfalls permanent');
INSERT INTO habitat_type (id, name) VALUES (178, 'Swamp - Rivers, seasonal streams, intermittent or irregular');
INSERT INTO habitat_type (id, name) VALUES (179, 'Swamp - Freshwater lakes Permantes');
INSERT INTO habitat_type (id, name) VALUES (180, 'Swamp - Freshwater lakes Sazonais/Intermitentes');
INSERT INTO habitat_type (id, name) VALUES (181, 'Swamp - Ponds / Wetlands / Puddles saline, brackish or alkaline');
INSERT INTO habitat_type (id, name) VALUES (182, 'Swamp - Ponds / Wetlands / Puddles saline, brackish or alkaline');
INSERT INTO habitat_type (id, name) VALUES (183, 'Swamp - Ponds / Wetlands / Pools');
INSERT INTO habitat_type (id, name) VALUES (184, 'Swamp - Ponds / Wetlands / Pools');
INSERT INTO habitat_type (id, name) VALUES (185, 'Swamp - Lakes saline, brackish or alkaline');
INSERT INTO habitat_type (id, name) VALUES (186, 'Swamp - Lakes saline, brackish or alkaline');
INSERT INTO habitat_type (id, name) VALUES (187, 'Swamp - Water sources');
INSERT INTO habitat_type (id, name) VALUES (188, 'Swamp - Carstes and other underground water systems');
INSERT INTO habitat_type (id, name) VALUES (189, 'Swamp - rocky areas');
INSERT INTO habitat_type (id, name) VALUES (190, 'Swamp - Caverns');
INSERT INTO habitat_type (id, name) VALUES (191, 'Swamp - introduced vegetation');
INSERT INTO habitat_type (id, name) VALUES (192, 'Swamp - Other');
INSERT INTO habitat_type (id, name) VALUES (193, 'Marine - Costões (incluindo ilhas rochosas ao longo da costa e penhascos marinhos)');
INSERT INTO habitat_type (id, name) VALUES (194, 'Marine - Sandy beaches, gravel and pebbles (including shoals, sandy islets, dune systems)');
INSERT INTO habitat_type (id, name) VALUES (195, 'Marine - estuarine waters');
INSERT INTO habitat_type (id, name) VALUES (196, 'Marine - Intertidal mud, sand or salt');
INSERT INTO habitat_type (id, name) VALUES (197, 'Marine - Marismas entremarés');
INSERT INTO habitat_type (id, name) VALUES (198, 'Marine - mangrove');
INSERT INTO habitat_type (id, name) VALUES (199, 'Marine - coastal lagoons salt or brackish');
INSERT INTO habitat_type (id, name) VALUES (200, 'Marine - coastal lagoons Freshwater');
INSERT INTO habitat_type (id, name) VALUES (201, 'Marine - intertidal');
INSERT INTO habitat_type (id, name) VALUES (202, 'Marine - Shallow subtidal (less than 6m deep, including bays and straits)');
INSERT INTO habitat_type (id, name) VALUES (203, 'Marine - open Sea');
INSERT INTO habitat_type (id, name) VALUES (204, 'Marine - Coral Reefs');
INSERT INTO habitat_type (id, name) VALUES (205, 'Marine - Gardens of algae, seaweed forests, Marine Meadows');
INSERT INTO habitat_type (id, name) VALUES (206, 'Marine - Other');

-- role data
INSERT INTO user_role (id, name, role) VALUES (1, 'ADMIN', 'ADMIN');
INSERT INTO user_role (id, name, role) VALUES (2, 'EXPERT', 'EXPERT');
INSERT INTO user_role (id, name, role) VALUES (3, 'PUBLIC_USER', 'PUBLIC_USER');
INSERT INTO user_role (id, name, role) VALUES (4, 'ANONYMOUS', 'ANONYMOUS');
INSERT INTO user_role (id, name, role) VALUES (5, 'SUPERADMIN', 'SUPERADMIN');

COMMIT;
