INSERT INTO habitat_type (id, name, code) VALUES (1, 'Amazonia - Rain Forest Alluvial', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (2, 'Amazonia - Rain Forest of the Lowlands', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (3, 'Amazonia - Rain Forest Submontane', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (4, 'Amazonia - Rain Forest Montana', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (5, 'Amazonia - Rain Forest Open Alluvial', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (6, 'Amazonia - Open Tropical Rain Forest of the Lowlands', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (7, 'Amazonia - Rain Forest Open Submontane', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (8, 'Amazonia - Semideciduous forest Alluvial', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (9, 'Amazonia - Semideciduous forest of the Lowlands', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (10, 'Amazonia - Semideciduous forest Submontane', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (11, 'Amazonia - Deciduous Forest Submontane', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (12, 'Amazonia - campinarana Forested', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (13, 'Amazonia - campinarana Tree', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (14, 'Amazonia - campinarana shrub', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (15, 'Amazonia - Campinarana Grassy-Woody', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (16, 'Amazonia - savannah Woodland', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (17, 'Amazonia - savannah Wooded', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (18, 'Amazonia - savannah Park', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (19, 'Amazonia - Savannah Grassy-Woody', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (20, 'Amazonia - Savannah Steppe Forested', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (21, 'Amazonia - Savannah Steppe Tree', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (22, 'Amazonia - Savannah Steppe Park', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (23, 'Amazonia - Savannah Steppe Grassy-woody', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (24, 'Amazonia - Vegetation with Marine Influence', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (25, 'Amazonia - Vegetation with Influence fluviomarinha', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (26, 'Amazonia - Vegetation with Fluvial Influence and / or Lakeside', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (27, 'Amazonia - Refuge vegetation Montano', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (28, 'Amazonia - cerradão', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (29, 'Amazonia - Cerrado field', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (30, 'Amazonia - field Dirty', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (31, 'Amazonia - Campo Limpo', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (32, 'Amazonia - mangrove', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (33, 'Amazonia - Rivers, streams, rapids and waterfalls permanent', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (34, 'Amazonia - Rivers, seasonal streams, intermittent or irregular', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (35, 'Amazonia - Lagos de água doce permanentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (36, 'Amazonia - Lagos de água doce sazonais/intermitentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (37, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas permanentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (38, 'Amazonia - Lagoas / Brejos / Poças salinas, salobras ou alcalinas sazonais/intermitentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (39, 'Amazonia - Lagoas / Brejos / Poças permanentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (40, 'Amazonia - Lagoas / Brejos / Poças sazonais/intermitentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (41, 'Amazonia - Lagos salinos, salobros ou alcalinos permanentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (42, 'Amazonia - Lagos salinos, salobros ou alcalinos sazonais/intermitentes', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (43, 'Amazonia - Nascentes de água ', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (44, 'Amazonia - Carstes e outros sistemas hidrológicos subterrâneos ', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (45, 'Amazonia - Áreas rochosas', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (46, 'Amazonia - Cavernas', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (47, 'Amazonia - Vegetação introduzida', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (48, 'Amazonia - Outros', 'AMA');
INSERT INTO habitat_type (id, name, code) VALUES (49, 'Mata Atlantica - Rain Forest of the Lowlands', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (50, 'Mata Atlantica - Rain Forest Submontane', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (51, 'Mata Atlantica - Rain Forest Montana', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (52, 'Mata Atlantica - Open Tropical Rain Forest', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (53, 'Mata Atlantica - Rain Forest Mista Montana', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (54, 'Mata Atlantica - Rain Forest Mixed Alto Montana', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (55, 'Mata Atlantica - Semideciduous forest Alluvial', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (56, 'Mata Atlantica - Semideciduous forest Submontane', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (57, 'Mata Atlantica - Semideciduous forest Montana', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (58, 'Mata Atlantica - Deciduous Forest Submontane', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (59, 'Mata Atlantica - steppe Park', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (60, 'Mata Atlantica - Steppe Grassy-Woody', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (61, 'Mata Atlantica - savannah Park', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (62, 'Mata Atlantica - Savannah Grassy-Woody', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (63, 'Mata Atlantica - Savannah Steppe Tree', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (64, 'Mata Atlantica - Vegetation with Marine Influence', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (65, 'Mata Atlantica - Vegetation with Influence fluviomarinha', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (66, 'Mata Atlantica - Vegetation with Fluvial Influence and / or Lakeside', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (67, 'Mata Atlantica - Refuge vegetation Montano', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (68, 'Mata Atlantica - Refuge vegetation High Montano', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (69, 'Mata Atlantica - rock fields', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (70, 'Mata Atlantica - Altitude fields', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (71, 'Mata Atlantica - field Dirty', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (72, 'Mata Atlantica - Campo Limpo', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (73, 'Mata Atlantica - Campo Limpo', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (74, 'Mata Atlantica - Semideciduous forest Submontane', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (75, 'Mata Atlantica - field Dirty', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (76, 'Mata Atlantica - Open Tropical Rain Forest', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (77, 'Mata Atlantica - Rain Forest of the Lowlands', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (78, 'Mata Atlantica - Campo Limpo', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (79, 'Mata Atlantica - mangrove', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (80, 'Mata Atlantica - Restinga', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (81, 'Mata Atlantica - Rivers, streams, rapids and waterfalls permanent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (82, 'Mata Atlantica - Rivers, seasonal streams, intermittent or irregular', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (83, 'Mata Atlantica - Freshwater lakes permanent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (84, 'Mata Atlantica - Freshwater lakes seasonal/intermittent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (85, 'Mata Atlantica - Ponds / Wetlands / Puddles saline, brackish or alkaline permanent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (86, 'Mata Atlantica - caves', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (87, 'Mata Atlantica - Ponds / Wetlands / Pools permanent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (88, 'Mata Atlantica - Ponds / Wetlands / Pools seasonal/intermittent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (89, 'Mata Atlantica - Lakes saline, brackish or alkaline permanent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (90, 'Mata Atlantica - Lakes saline, brackish or alkaline seasonal/intermittent', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (91, 'Mata Atlantica - Water sources', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (92, 'Mata Atlantica - Carstes and other underground water systems', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (93, 'Mata Atlantica - rocky areas', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (94, 'Mata Atlantica - caves', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (95, 'Mata Atlantica - introduced vegetation', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (96, 'Mata Atlantica - other', 'MAT');
INSERT INTO habitat_type (id, name, code) VALUES (97, 'Closed - savanna Woodland', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (98, 'Closed - savanna Wooded', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (99, 'Closed - savannah Park', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (100, 'Closed - Savannah Grassy-Woody', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (101, 'Closed - Semideciduous forest', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (102, 'Closed - Deciduous Forest', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (103, 'Closed - Vegetation with Marine Influence', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (104, 'Closed - Vegetation with Influence fluviomarinha', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (105, 'Closed - Refuge vegetation Montano', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (106, 'Closed - Rupestres fields', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (107, 'Closed - closed', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (108, 'Closed - Cerrado field', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (109, 'Closed - Campo Sujo', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (110, 'Closed - field Dirty', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (111, 'Closed - Rivers, streams, rapids and waterfalls permanent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (112, 'Closed - Rivers, seasonal streams, intermittent or irregular', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (113, 'Closed - Freshwater lakes permanent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (114, 'Closed - Freshwater lakes Seasonal / Intermittent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (115, 'Closed - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (116, 'Closed - Ponds / Wetlands / Puddles saline, brackish or alkaline Seasonal / Intermittent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (117, 'Closed - Ponds / Wetlands / Pools Permanentes', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (118, 'Closed - Ponds / Wetlands / Pools Seasonal / Intermittent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (119, 'Closed - Lakes saline, brackish or alkaline Permanentes', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (120, 'Closed - Lakes saline, brackish or alkaline Seasonal / Intermittent', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (121, 'Closed - Water sources', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (122, 'Closed - Carstes and other underground water systems', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (123, 'Closed - Cavernas', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (124, 'Closed - introduced vegetation', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (125, 'Closed - Other', 'CLO');
INSERT INTO habitat_type (id, name, code) VALUES (126, 'Caatinga - Freshwater lakes permanent', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (127, 'Caatinga - Freshwater lakes Seasonal / Intermittent', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (128, 'Caatinga - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (129, 'Caatinga - Ponds / Wetlands / Puddles saline, brackish or alkaline Seasonal / Intermittent', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (130, 'Caatinga - Ponds / Wetlands / Pools Permanentes', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (131, 'Caatinga - Ponds / Wetlands / Pools Seasonal / Intermittent', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (132, 'Caatinga - Lakes saline, brackish or alkaline Permanentes', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (133, 'Caatinga - Lakes saline, brackish or alkaline Seasonal / Intermittent', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (134, 'Caatinga - Water sources', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (135, 'Caatinga - Carstes and other underground water systems', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (136, 'Caatinga - caves', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (137, 'Caatinga - introduced vegetation', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (138, 'Caatinga - Other', 'CAA');
INSERT INTO habitat_type (id, name, code) VALUES (139, 'Pampa - steppe Tree', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (140, 'Pampa - steppe Park', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (141, 'Pampa - Steppe Grassy-Woody', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (142, 'Pampa - Savannah Steppe Park', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (143, 'Pampa - Semideciduous forest', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (144, 'Pampa - Vegetation with Marine Influence', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (145, 'Pampa - Sulinos fields', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (146, 'Pampa - Rivers, streams, rapids and waterfalls permanent', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (147, 'Pampa - Rivers, seasonal streams, intermittent or irregular', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (148, 'Pampa - Freshwater lakes Permanentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (149, 'Pampa - Freshwater lakes Sazonais/Intermitentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (150, 'Pampa - Ponds / Wetlands / Puddles saline, brackish or alkaline Permanentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (151, 'Pampa - Ponds / Wetlands / Puddles saline, brackish or alkaline Sazonais/Intermitentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (152, 'Pampa - Ponds / Wetlands / Pools Permanentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (153, 'Pampa - Ponds / Wetlands / Pools Sazonais/Intermitentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (154, 'Pampa - Lakes saline, brackish or alkaline Permanentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (155, 'Pampa - Lakes saline, brackish or alkaline Sazonais/Intermitentes', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (156, 'Pampa - Water sources', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (157, 'Pampa - Carstes and other underground water systems', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (158, 'Pampa - rocky areas', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (159, 'Pampa - Caverns', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (160, 'Pampa - introduced vegetation', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (161, 'Pampa - Other', 'PAM');
INSERT INTO habitat_type (id, name, code) VALUES (162, 'Swamp - Semideciduous forest Alluvial', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (163, 'Swamp - Deciduous Forest of Lowlands', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (164, 'Swamp - Deciduous Forest Submontane', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (165, 'Swamp - savanna Woodland', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (166, 'Swamp - savana Wooded', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (167, 'Swamp - savannah Park', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (168, 'Swamp - Savannah Grassy-Woody', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (169, 'Swamp - Savannah Steppe Forested', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (170, 'Swamp - Savannah Steppe Tree', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (171, 'Swamp - Savannah Steppe Park', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (172, 'Swamp - Savannah Steppe Park', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (173, 'Swamp - Cerradão', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (174, 'Swamp - Cerrado field', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (175, 'Swamp - field Dirty', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (176, 'Swamp - Campo Limpo', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (177, 'Swamp - Rivers, streams, rapids and waterfalls permanent', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (178, 'Swamp - Rivers, seasonal streams, intermittent or irregular', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (179, 'Swamp - Freshwater lakes Permantes', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (180, 'Swamp - Freshwater lakes Sazonais/Intermitentes', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (181, 'Swamp - Ponds / Wetlands / Puddles saline, brackish or alkaline', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (182, 'Swamp - Ponds / Wetlands / Puddles saline, brackish or alkaline', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (183, 'Swamp - Ponds / Wetlands / Pools', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (184, 'Swamp - Ponds / Wetlands / Pools', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (185, 'Swamp - Lakes saline, brackish or alkaline', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (186, 'Swamp - Lakes saline, brackish or alkaline', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (187, 'Swamp - Water sources', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (188, 'Swamp - Carstes and other underground water systems', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (189, 'Swamp - rocky areas', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (190, 'Swamp - Caverns', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (191, 'Swamp - introduced vegetation', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (192, 'Swamp - Other', 'SWA');
INSERT INTO habitat_type (id, name, code) VALUES (193, 'Marine - Costões (incluindo ilhas rochosas ao longo da costa e penhascos marinhos)', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (194, 'Marine - Sandy beaches, gravel and pebbles (including shoals, sandy islets, dune systems)', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (195, 'Marine - estuarine waters', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (196, 'Marine - Intertidal mud, sand or salt', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (197, 'Marine - Marismas entremarés', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (198, 'Marine - mangrove', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (199, 'Marine - coastal lagoons salt or brackish', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (200, 'Marine - coastal lagoons Freshwater', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (201, 'Marine - intertidal', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (202, 'Marine - Shallow subtidal (less than 6m deep, including bays and straits)', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (203, 'Marine - open Sea', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (204, 'Marine - Coral Reefs', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (205, 'Marine - Gardens of algae, seaweed forests, Marine Meadows', 'MAR');
INSERT INTO habitat_type (id, name, code) VALUES (206, 'Marine - Other', 'MAR');