package com.unep.wcmc.model;

public enum PopulationDeclinedBasedOn {

    DIRECT_OBSERVATION,
    INDEX_ABUNDANCE_APPROPRIATE_TAXON,
    DECLINE_AOC_EOC_HABITAT_QUALITY,
    ACTUAL_POTENTIAL_LEVEL_EXPLOITATION,
    EFFECTS_INTRODUCED_TAXA_HIBRIDIZATION_PATHOGENS_ETC

}
