package com.unep.wcmc.model;


public enum TropicPosition {

   AQUATIC_PRIMARY_CONSUMERS,
   AQUATIC_PRIMARY_PRODUCER,
   AQUATIC_QUATERNARY_CONSUMERS,
   AQUATIC_TERTIARY_CONSUMERS,
   SECONDARY_CONSUMERS,
   TERRESTRIAL_PRIMARY_CONSUMERS,
   TERRESTRIAL_PRIMARY_PRODUCER,
   TERRESTRIAL_QUATERNARY_CONSUMERS,
   TERRESTRIAL_TERTIARY_CONSUMERS
}
